import { internalMutation } from "./_generated/server";
import { v } from "convex/values";

const VETS = [
  {
    name: "Aavc-Animal & Avian Veterinary Clinic",
    block: "716",
    street: "YISHUN STREET 71",
    floor: "1",
    unit: "254",
    postalCode: "760716",
    openingHours: "Mon–Fri 10am–1:30pm, 5pm–7:30pm · Sat–Sun 10am–1:30pm",
    phone: "6853 9397",
    area: "",
    emergency: "",
    publicHolidays: true,
    lat: 1.4260879,
    lng: 103.8275646,
    website: "https://aavcsg.wixsite.com/aavc",
  },
  {
    name: "Acacia Vet & Surgery",
    block: "338",
    street: "ANG MO KIO AVENUE 1",
    floor: "1",
    unit: "1671",
    building: "TECK GHEE COURT",
    postalCode: "560338",
    openingHours:
      "Mon 10am–2pm, 4pm–8pm · Tue Closed · Wed–Fri 10am–2pm, 4pm–8pm · Sat–Sun 10am–1pm, 2pm–5pm",
    phone: "+65 6481 6889",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3640641,
    lng: 103.8486625,
    website: "https://acaciavetandsurgery.wordpress.com/contact/",
    instagram: "https://www.instagram.com/acacia_vet",
  },
  {
    name: "Ace Vet Care",
    block: "271",
    street: "BALESTIER ROAD",
    building: "VICTORY POINT",
    postalCode: "329722",
    openingHours:
      "Mon–Fri 9:30am–12:30pm, 2pm–4:30pm, 6pm–8:30pm · Sat–Sun 9:30am–12:30pm, 2pm–6:30pm",
    phone: "+65 6258 2159",
    area: "",
    emergency: "",
    publicHolidays: true,
    lat: 1.322446,
    lng: 103.8526366,
    website: "https://acevetcare.sg/",
    instagram: "https://www.instagram.com/acevetsg",
  },
  {
    name: "Advanced Vetcare",
    block: "26",
    street: "JALAN PARI BURONG",
    building: "PICARDY GARDEN",
    postalCode: "488692",
    openingHours: "",
    phone: "",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3337747,
    lng: 103.9486821,
  },
  {
    name: "Advanced Vetcare",
    block: "18",
    street: "JALAN PARI BURONG",
    building: "PICARDY GARDEN",
    postalCode: "488684",
    openingHours: "Mon–Sun 24 hours",
    phone: "6636 1788",
    area: "",
    emergency: "6636 1788",
    publicHolidays: true,
    lat: 1.3336061,
    lng: 103.948412,
    website: "https://www.advancedvetcare.sg/",
  },
  {
    name: "Advanced Vetcare",
    block: "283",
    street: "OUTRAM ROAD",
    postalCode: "169068",
    openingHours: "Mon Closed · Tue–Sun 9am–9pm",
    phone: "6575 1788",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.2857027,
    lng: 103.8345605,
    website: "https://www.advancedvetcare.sg/",
  },
  {
    name: "Advanced Vetcare @ Balestier",
    block: "564A",
    street: "BALESTIER ROAD",
    postalCode: "329880",
    openingHours: "Mon 9am–9pm · Tue Closed · Wed–Sun 9am–9pm",
    phone: "6565 1788",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3268912,
    lng: 103.844446,
    website: "https://www.advancedvetcare.sg/",
  },
  {
    name: "Allpets & Aqualife Vets Pte Ltd",
    block: "24",
    street: "JALAN KELULUT",
    floor: "1",
    unit: "1",
    postalCode: "809041",
    openingHours: "Mon–Sat 9:30am–1pm, 3pm–7:30pm · Sun Closed",
    phone: "6481 3700",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3833683,
    lng: 103.8756884,
    website: "https://www.advancedvetcare.sg/",
    instagram: "https://www.instagram.com/allpetsaqualife",
  },
  // {
  //   name: "Amber Cat Vet Pte Ltd",
  //   block: "48",
  //   street: "BURNFOOT TERRACE",
  //   building: "FRANKEL ESTATE",
  //   postalCode: "459836",
  //   openingHours: "",
  //   phone: "",
  //   area: "",
  //   emergency: "",
  //   publicHolidays: false,
  //   website: "https://ambercatvet.com/",
  // },
  {
    name: "Amber Veterinary Practice Pte Ltd",
    block: "50",
    street: "BURNFOOT TERRACE",
    postalCode: "459837",
    openingHours:
      "Mon–Fri 9:30am–12pm, 2:30pm–7pm · Sat 9:30am–1pm · Sun Closed",
    phone: "+65 6245 5543",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3126422,
    lng: 103.9227259,
    website: "https://ambervet.com/",
    instagram: "https://www.instagram.com/ambervet",
  },
  {
    name: "Animal Medical Centre (Vet@Rv)",
    block: "78",
    street: "INDUS ROAD",
    floor: "1",
    unit: "487",
    postalCode: "161078",
    openingHours:
      "Mon 2pm–4pm, 9pm–10pm · Tue Closed · Wed 2pm–4pm · Thu 2pm–4pm, 9pm–10pm · Fri 2pm–4pm · Sat 2pm–5pm · Sun Closed",
    phone: "6271 0665",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.2915025,
    lng: 103.8271968,
    website: "https://www.vetatrv.com/",
  },
  {
    name: "Animal Wellness Centre Pte Ltd",
    block: "1",
    street: "VISTA EXCHANGE GREEN",
    floor: "1",
    unit: "15",
    building: "THE STAR",
    postalCode: "138617",
    openingHours: "Mon–Sat 9am–7pm · Sun Closed",
    phone: "+65 6694 6383",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3068072,
    lng: 103.7883997,
    website: "https://animalwellness.sg/",
    instagram: "https://www.instagram.com/awcsingapore",
  },
  {
    name: "Animal Wellness Referral Centre Pte Ltd",
    block: "200",
    street: "BUKIT TIMAH ROAD",
    floor: "1",
    unit: "1",
    building: "ATLAND HOUSE",
    postalCode: "229862",
    openingHours:
      "Mon–Wed 9am–12am · Thu 9am–7pm · Fri–Sat 9am–12am · Sun 9am–7pm",
    phone: "+65 6530 3530",
    area: "",
    emergency: "+65 6530 3530",
    publicHolidays: false,
    lat: 1.3118492,
    lng: 103.8420819,
    website: "https://www.awrc.sg/",
  },
  {
    name: "Animal World Veterinary Clinic",
    block: "16",
    street: "YIO CHU KANG ROAD",
    floor: "1",
    postalCode: "545527",
    openingHours: "Mon–Sat 9:30am–7:30pm · Sun 9:30am–1:30pm",
    phone: "+65 6286 0929",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3546704,
    lng: 103.8775449,
    website: "https://www.animalworldclinic.com/",
  },
  {
    name: "Apex Veterinary Clinic",
    block: "462",
    street: "RIVER VALLEY ROAD",
    unit: "462",
    postalCode: "248347",
    openingHours: "",
    phone: "6767 3369",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.2938066,
    lng: 103.8265932,
    website: "https://www.apexvetclinic.com/",
    instagram: "https://www.instagram.com/apexvets/",
  },
  {
    name: "Apex Veterinary Medical Centre Pte Ltd Punggol",
    block: "418",
    street: "NORTHSHORE DRIVE",
    floor: "2",
    unit: "213",
    postalCode: "820418",
    openingHours: "",
    phone: "6518 3233",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.4176858,
    lng: 103.9010984,
    website: "https://www.apexvetclinic.com/",
    instagram: "https://www.instagram.com/apexvets/",
  },
  {
    name: "Apex Veterinary Clinic",
    block: "416",
    street: "Ang Mo Kio Ave 10",
    floor: "01",
    unit: "973",
    postalCode: "560416",
    openingHours: "",
    phone: "6386 9883",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3645899,
    lng: 103.8550908,
    website: "https://www.apexvetclinic.com/",
    instagram: "https://www.instagram.com/apexvets/",
  },
  // {
  //   name: "Atlas Veterinary Clinic & Surgery",
  //   block: "163",
  //   street: "BUKIT MERAH CENTRAL",
  //   floor: "3",
  //   unit: "3579",
  //   postalCode: "150163",
  //   openingHours: "",
  //   phone: "",
  //   area: "",
  //   emergency: "",
  //   publicHolidays: false,
  //   website: "https://www.atlasvet.com.sg/"
  // },
  {
    name: "Atlas Veterinary Clinic & Surgery",
    block: "163",
    street: "BUKIT MERAH CENTRAL",
    floor: "3",
    unit: "3573",
    postalCode: "150163",
    openingHours:
      "Mon–Fri 10am–12:30pm, 2pm–6:30pm · Sat–Sun 10am–12:30pm, 2pm–4:30pm",
    phone: "6980 8038",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.2840007,
    lng: 103.8171301,
    website: "https://www.atlasvet.com.sg/",
    instagram: "https://www.instagram.com/atlasvetsg/",
  },
  {
    name: "Avh Animal Ark Veterinary Group",
    block: "139",
    street: "TAMPINES STREET 11",
    floor: "1",
    unit: "54",
    postalCode: "521139",
    openingHours: "Mon–Sun 10am–1pm, 2pm–8pm",
    phone: "+65 6587 1798",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3461213,
    lng: 103.9445369,
    website: "https://www.arkvet.com.sg/",
    instagram: "https://www.instagram.com/theanimalarkvet/",
  },
  {
    name: "Avh Animal Ark Veterinary Group (Springleaf)",
    block: "5",
    street: "MANDAI ROAD",
    postalCode: "779391",
    openingHours: "Mon–Sun 10am–1pm, 2pm–8pm",
    phone: "+65 6467 3287",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.402302,
    lng: 103.8167289,
    website: "https://www.arkvet.com.sg/",
    instagram: "https://www.instagram.com/theanimalarkvet/",
  },
  {
    name: "Barkway Pet Health Pte. Ltd.",
    block: "169",
    street: "MACPHERSON ROAD",
    floor: "1",
    postalCode: "348535",
    openingHours:
      "Mon–Fri 9:30am–12:30pm, 2pm–4:30pm, 6pm–8pm · Sat–Sun 9:30am–12:30pm, 2pm–4:30pm",
    phone: "6904 4300 / 6904 4301",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3298678,
    lng: 103.8738567,
    website: "https://barkway.sg/",
    instagram: "https://www.instagram.com/barkway.sg/",
  },
  {
    name: "Beecroft Animal Specialist And Emergency Hospital",
    block: "991E",
    street: "ALEXANDRA ROAD",
    floor: "1",
    unit: "27",
    postalCode: "119973",
    openingHours: "Mon–Sun 24 hours",
    phone: "+65 6996 1812",
    area: "",
    emergency: "+65 6996 1812",
    publicHolidays: true,
    lat: 1.2732751,
    lng: 103.8029433,
    website: "https://beecroft.com.sg/",
    instagram: "https://www.instagram.com/beecroftsgvet/",
  },
  {
    name: "Bluewater Vet Acupuncture & Rehabilitation",
    block: "16",
    street: "SIN MING ROAD",
    floor: "1",
    unit: "9",
    building: "SIN MING PLAZA",
    postalCode: "575585",
    openingHours:
      "Mon–Fri 10am–1pm, 2pm–7pm · Sat 9am–1pm, 2pm–4pm · Sun Closed",
    phone: "+65 6816 1629 / +65 8775 3041",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3537375,
    lng: 103.8359324,
    website: "https://bluewatervetacupuncture.sg/",
    instagram: "https://www.instagram.com/bluewatervetacupuncture/",
  },
  {
    name: "Brighton Vet Care (Bukit Timah)",
    block: "611",
    street: "BUKIT TIMAH ROAD",
    postalCode: "269712",
    openingHours:
      "Mon–Wed 10am–2pm, 3pm–7pm · Thu Closed · Fri–Sun 10am–2pm, 3pm–7pm",
    phone: "+65 6235 2250",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3243992,
    lng: 103.8094825,
    website: "https://www.brightonvetcare.com/",
    instagram: "https://www.instagram.com/brightonvetcare",
  },
  {
    name: "Brighton Vet Care (Katong)",
    block: "438",
    street: "JOO CHIAT ROAD",
    postalCode: "427651",
    openingHours:
      "Mon–Tue 10am–3pm, 4pm–9pm · Wed Closed · Thu–Fri 10am–3pm, 4pm–9pm · Sat–Sun 10am–3pm",
    phone: "+65 6214 9521",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.306683,
    lng: 103.9042814,
    website: "https://brightonvetcare.com/pages/katong",
    instagram: "https://www.instagram.com/brightonvetcare",
  },
  {
    name: "Brighton Vet Care (Serangoon Garden)",
    block: "74",
    street: "SERANGOON GARDEN WAY",
    building: "SERANGOON GARDEN ESTATE",
    postalCode: "555970",
    openingHours: "Mon–Sun 10am–2pm, 3pm–7pm",
    phone: "+65 6282 2484",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3639688,
    lng: 103.8658082,
    website: "https://www.brightonvetcare.com/",
    instagram: "https://www.instagram.com/brightonvetcare",
  },
  {
    name: "Canopy Veterinary Centre",
    block: "1",
    street: "YUAN CHING ROAD",
    floor: "3",
    unit: "3",
    building: "SUPERBOWL JURONG",
    postalCode: "618640",
    openingHours:
      "Mon–Tue 10am–8:30pm · Wed Closed · Thu–Fri 10am–8:30pm · Sat–Sun 10am–5:30pm",
    phone: "+65 6980 8582",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3257886,
    lng: 103.7243194,
    website: "https://canopyvets.com/",
  },
  {
    name: "Care Veterinary Clinic Pte Ltd",
    block: "124",
    street: "LORONG 1 TOA PAYOH",
    floor: "1",
    unit: "473",
    postalCode: "310124",
    openingHours:
      "Mon 9:30am–12pm, 2pm–5pm, 6pm–8pm · Tue Closed · Wed–Fri 9:30am–12pm, 2pm–5pm, 6pm–8pm · Sat–Sun 10am–1pm, 2pm–5pm",
    phone: "+65 6250 0535",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3386669,
    lng: 103.8443465,
    website: "https://carevetclinic.com.sg/wp/",
  },
  {
    name: "Clinic For Pets",
    block: "1015",
    street: "GEYLANG EAST AVENUE 3",
    floor: "1",
    unit: "141",
    building: "GEYLANG EAST INDUSTRIAL ESTATE",
    postalCode: "389730",
    openingHours: "",
    phone: "",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3187414,
    lng: 103.8907817,
    website: "https://www.facebook.com/457812597615354/",
  },
  {
    name: "Clover Vet",
    block: "678",
    street: "HOUGANG AVENUE 8",
    floor: "1",
    unit: "503",
    postalCode: "530678",
    openingHours: "Mon–Fri 9am–9pm · Sat 9am–5pm · Sun Closed",
    phone: "+65 6518 9678",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3708467,
    lng: 103.8839842,
    website: "https://www.clovervet.sg/",
    instagram: "https://www.instagram.com/clovervetsg",
  },
  {
    name: "Companion Animal Surgery Pte Ltd",
    block: "12",
    street: "BOON TECK ROAD",
    floor: "1",
    unit: "5",
    postalCode: "329586",
    openingHours: "Mon–Sun 24 hours",
    phone: "+65 6255 7950",
    area: "",
    emergency: "+65 6255 7950",
    publicHolidays: false,
    lat: 1.3260969,
    lng: 103.8496214,
    website: "https://www.comvet.com/",
  },
  {
    name: "Dr Paws Vet Care",
    block: "77",
    street: "LUCKY HEIGHTS",
    building: "LUCKY COURT",
    postalCode: "467626",
    openingHours:
      "Mon–Wed 10am–8pm · Thu Closed · Fri–Sat 10am–8pm · Sun Closed",
    phone: "+65 6243 4668",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3183592,
    lng: 103.9414667,
    website: "https://drpawsvetcare.com/",
    instagram: "https://www.instagram.com/drpawsvetcaresg",
  },
  {
    name: "Edmond Tan Veterinary Surgery",
    block: "151",
    street: "Serangoon North Avenue 2",
    floor: "1",
    unit: "65",
    postalCode: "550151",
    openingHours: "",
    phone: "",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3695973,
    lng: 103.8742136,
    website:
      "https://www.facebook.com/pages/Edmond-Tan-Veterinary-Surgery/194064770615689",
  },
  {
    name: "Evervet Veterinary Clinic",
    block: "212",
    street: "CHANGI ROAD",
    floor: "1",
    unit: "212",
    postalCode: "419735",
    openingHours:
      "Mon–Wed 9:30am–1pm, 2pm–7:30pm · Thu–Fri 9:30am–12pm, 2pm–5pm, 6pm–9pm · Sat 9:30am–1pm, 2pm–5pm · Sun Closed",
    phone: "+65 6513 8138 / 6513 0836",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3171104,
    lng: 103.9039091,
    website: "https://www.evervetsg.com/",
    instagram: "https://www.instagram.com/evervetsg",
  },
  {
    name: "Evervet Veterinary Clinic Pte Ltd",
    block: "123",
    street: "BEDOK NORTH STREET 2",
    floor: "1",
    unit: "154",
    postalCode: "460123",
    openingHours:
      "Mon–Tue 9:30am–12pm, 2pm–5pm, 6pm–9pm · Wed–Fri 9:30am–1pm, 2pm–7:30pm · Sat 9:30am–12pm, 2pm–5pm · Sun Closed",
    phone: "+65 6449 4491 / 6241 1477",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3291933,
    lng: 103.9372982,
    website: "https://www.evervetsg.com/",
    instagram: "https://www.instagram.com/evervetsg",
  },
  {
    name: "Frankel Veterinary Centre",
    block: "101",
    street: "FRANKEL AVENUE",
    floor: "1",
    postalCode: "458224",
    openingHours:
      "Mon–Fri 9am–12:30pm, 2pm–5pm, 6pm–8:30pm · Sat 9am–1pm, 2pm–4:30pm · Sun Closed",
    phone: "+65 6876 1212",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3146101,
    lng: 103.9193424,
    website: "https://frankelvet.com.sg/",
  },
  {
    name: "Fur Folks Home",
    block: "1212",
    street: "UPPER THOMSON ROAD",
    floor: "1",
    postalCode: "787127",
    openingHours: "",
    phone: "",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3725206,
    lng: 103.8285173,
    website: "https://www.vetmobilesg.com/furfolkshome/",
    instagram: "https://www.instagram.com/vetmobile.sg",
  },
  {
    name: "Furiends Veterinary Clinic",
    block: "58",
    street: "YIO CHU KANG ROAD",
    postalCode: "545564",
    openingHours:
      "Mon–Tue 10am–1pm, 4pm–8pm · Wed Closed · Thu–Fri 10am–1pm, 4pm–8pm · Sat 10am–4pm · Sun Closed",
    phone: "+65 6244 2112",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.357249,
    lng: 103.8757509,
    website: "https://furiends.com.sg/",
  },
  {
    name: "Furrytails Veterinary Clinic Pte Ltd",
    block: "2",
    street: "JALAN LOKAM",
    building: "KENSINGTON SQUARE",
    postalCode: "537846",
    openingHours:
      "Mon–Fri 9:30am–12:30pm, 2pm–5pm, 6pm–8pm · Sat–Sun 9:30am–12:30pm, 2pm–5pm",
    phone: "6214 9092",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3456397,
    lng: 103.8826924,
    website: "https://furrytailsvet.com.sg/",
    instagram: "https://www.instagram.com/furrytailsvet",
  },
  {
    name: "Gaia Veterinary Centre (Jalan Besar)",
    block: "415",
    street: "JALAN BESAR",
    postalCode: "209016",
    openingHours: "Mon–Fri 10am–10pm · Sat–Sun 9am–9pm",
    phone: "6950 4533",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3141229,
    lng: 103.8598963,
    website: "https://gaiavets.com/vet-clinic-serangoon-road",
  },
  {
    name: "Gaia Veterinary Centre (Parksuites)",
    block: "24",
    street: "HOLLAND GROVE ROAD",
    floor: "1",
    unit: "12",
    building: "PARKSUITES",
    postalCode: "278803",
    openingHours: "Mon–Fri 10am–10pm · Sat–Sun 9am–5pm",
    phone: "6727 7511",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3168987,
    lng: 103.7830045,
    website: "https://gaiavets.com/vet-clinic-holland-road",
  },
  {
    name: "Genesis Veterinary Clinic",
    block: "935",
    street: "YISHUN CENTRAL 1",
    floor: "1",
    unit: "43",
    postalCode: "760935",
    openingHours:
      "Mon–Tue 9:30am–7pm · Wed 10am–5pm · Thu–Fri 9:30am–7pm · Sat 10am–5pm · Sun 10am–3pm",
    phone: "6257 0682",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.4251658,
    lng: 103.8368105,
    website: "https://www.genesisvet.com.sg/",
    instagram: "https://www.instagram.com/genesisvet",
  },
  {
    name: "Gentle Oak Veterinary Clinic",
    block: "21",
    street: "GHIM MOH ROAD",
    floor: "1",
    unit: "225",
    postalCode: "270021",
    openingHours: "Mon–Sun 9am–12pm, 2pm–7pm",
    phone: "6250 8001",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3103728,
    lng: 103.7890444,
    website: "https://www.gentleoakvet.com.sg/",
    instagram: "https://www.instagram.com/gentleoakvet",
  },
  {
    name: "Hillside Veterinary Surgery",
    block: "787A",
    street: "UPPER SERANGOON ROAD",
    postalCode: "534655",
    openingHours:
      "Mon–Fri 9:30am–12:30pm, 2pm–4:30pm, 6pm–8:30pm · Sat–Sun 9:30am–12:30pm, 2pm–4:30pm",
    phone: "6909 5338",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3553788,
    lng: 103.8796112,
    website: "https://www.hillsidevets.com.sg/",
    instagram: "https://www.instagram.com/hillsidevetsurgery",
  },
  {
    name: "Hope Veterinary Care",
    block: "1017",
    street: "UPPER SERANGOON ROAD",
    floor: "1",
    unit: "1",
    postalCode: "534755",
    openingHours: "Mon–Fri 9am–8pm · Sat 9am–5pm · Sun Closed",
    phone: "6518 9116",
    area: "",
    emergency: "6266 0232",
    publicHolidays: false,
    lat: 1.3576174,
    lng: 103.8824871,
    website: "https://www.hopeveterinarycare.sg/",
    instagram: "https://www.instagram.com/hopevetcare",
  },
  {
    name: "Island Veterinary Clinic Pte Ltd",
    block: "114",
    street: "JURONG EAST STREET 13",
    floor: "1",
    unit: "404",
    postalCode: "600114",
    openingHours:
      "Mon–Fri 9am–1pm, 2pm–7:30pm · Sat 9am–1pm, 2pm–5pm · Sun Closed",
    phone: "6560 5991",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3393855,
    lng: 103.7346674,
    website: "https://www.ivc.com.sg/",
    instagram: "https://www.instagram.com/ivcjurong",
  },
  {
    name: "James Tan Veterinary Centre Pte Ltd",
    block: "230",
    street: "WHITLEY ROAD",
    building: "JAMES TAN HOSPITAL",
    postalCode: "297823",
    openingHours:
      "Mon 9am–12pm, 2pm–5pm, 6:30pm–9pm · Tue–Fri 9am–12pm, 2pm–7:30pm · Sat 9am–12pm · Sun Closed",
    phone: "6253 1122",
    area: "",
    emergency: "",
    publicHolidays: true,
    lat: 1.3259106,
    lng: 103.8272864,
    website: "https://jtvet.com/",
  },
  {
    name: "Jireh Veterinary Clinic Pte Ltd",
    block: "530",
    street: "BALESTIER ROAD",
    floor: "1",
    unit: "4",
    postalCode: "329857",
    openingHours: "",
    phone: "",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3271771,
    lng: 103.8455156,
    website: "https://jirehvets.com/",
  },
  {
    name: "Kai Vets Pte Ltd",
    block: "144",
    street: "TAMPINES STREET 12",
    floor: "1",
    unit: "392",
    postalCode: "521144",
    openingHours: "Mon–Sat 9:30am–12pm, 2pm–7pm · Sun Closed",
    phone: "6980 8504",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3483959,
    lng: 103.9436804,
    website: "https://kaivets.com/",
    instagram: "https://www.instagram.com/kai_vets",
  },
  {
    name: "Kin Veterinary Clinic",
    block: "780",
    street: "UPPER BUKIT TIMAH ROAD",
    postalCode: "678125",
    openingHours:
      "Mon–Fri 9:30am–1pm, 2pm–8:30pm · Sat–Sun 9:30am–1pm, 2pm–5:30pm",
    phone: "6908 2980",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.372033,
    lng: 103.763238,
    website: "https://www.kinvet.sg/",
    instagram: "https://www.instagram.com/kinvetsg",
  },
  {
    name: "Landon Veterinary Specialist Hospital",
    block: "41",
    street: "ENG KONG TERRACE",
    building: "ENG KONG PARK",
    postalCode: "599013",
    openingHours: "Mon–Fri 9am–7pm · Sat–Sun Closed",
    phone: "+65 6463 7228",
    area: "",
    emergency: "+65 6463 7228",
    publicHolidays: false,
    lat: 1.3361644,
    lng: 103.7689093,
    website: "https://www.lvs.com.sg/",
    instagram: "https://www.instagram.com/landonvetspecialists",
  },
  {
    name: "Light Of Life Veterinary Clinic And Services Llp",
    block: "703",
    street: "Bedok Reservoir Road",
    floor: "1",
    unit: "3508",
    postalCode: "470703",
    openingHours:
      "Mon–Tue Closed · Wed 5pm–10pm · Thu–Sat 2pm–4pm, 5pm–10pm · Sun 5pm–10pm",
    phone: "6243 3282",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3371946,
    lng: 103.9198822,
    website: "https://www.lightoflifeveterinaryclinic.com/",
    instagram: "https://www.instagram.com/lightoflifevet",
  },
  {
    name: "Maranatha Veterinary Clinic",
    block: "77",
    street: "TELOK BLANGAH DRIVE",
    floor: "1",
    unit: "234",
    postalCode: "100077",
    openingHours:
      "Mon–Thu 8:30am–5:30pm · Fri 10am–4pm · Sat 7:30am–1pm · Sun Closed",
    phone: "6273 0100",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.2739369,
    lng: 103.8091415,
    website: "https://www.facebook.com/maranathavetclinic/",
    instagram: "https://www.instagram.com/maranathavetclinic",
  },
  {
    name: "Monster Pet Vet",
    block: "6",
    street: "EVERTON PARK",
    floor: "1",
    unit: "16",
    postalCode: "80006",
    openingHours: "",
    phone: "+65 6327 9148",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.2767598,
    lng: 103.8389235,
    website: "https://www.monsterpetvet.com/",
    instagram: "https://www.instagram.com/monsterpetvetclinicsg",
  },
  {
    name: "Mount Pleasant Animal Medical Centre (Bedok)",
    block: "158",
    street: "BEDOK SOUTH AVENUE 3",
    floor: "1",
    unit: "577",
    postalCode: "460158",
    openingHours:
      "Mon–Fri 9:30am–1pm, 2pm–7pm · Sat–Sun 9:30am–1pm, 2pm–5:30pm",
    phone: "6444 3561",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3187592,
    lng: 103.9450805,
    website: "https://www.mountpleasant.com.sg/locations/bedok/",
    instagram: "https://www.instagram.com/mountpleasantvetgroup",
  },
  {
    name: "Mount Pleasant Animal Medical Centre (Clementi)",
    block: "105",
    street: "CLEMENTI STREET 12",
    floor: "1",
    unit: "18",
    building: "SUNSET WAY RESIDENCE",
    postalCode: "120105",
    openingHours:
      "Mon–Fri 9:30am–12:30pm, 2pm–7pm · Sat–Sun 9:30am–12:30pm, 2pm–7pm",
    phone: "6776 8858",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.322682,
    lng: 103.7698766,
    website: "https://www.mountpleasant.com.sg/locations/clementi/",
    instagram: "https://www.instagram.com/mountpleasantvetgroup",
  },
  {
    name: "Mount Pleasant Animal Medical Centre (Farrer)",
    block: "3",
    street: "QUEEN'S ROAD",
    floor: "2",
    unit: "141",
    building: "FARRER GARDENS",
    postalCode: "260003",
    openingHours:
      "Mon–Fri 9:30am–1pm, 2pm–7:30pm · Sat–Sun 9:30am–1pm, 2pm–5pm",
    phone: "6271 1132",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3184044,
    lng: 103.808123,
    website: "https://www.mountpleasant.com.sg/locations/farrer/",
    instagram: "https://www.instagram.com/mountpleasantvetgroup",
  },
  {
    name: "Mount Pleasant Veterinary Centre (2008)",
    block: "2",
    street: "JALAN GELENGGANG",
    building: "SEMBAWANG HILLS ESTATE",
    postalCode: "578187",
    openingHours:
      "Mon–Fri 9:30am–12:30pm, 2pm–11pm · Sat–Sun 9:30am–12:30pm, 2pm–4:30pm",
    phone: "6251 7666",
    area: "",
    emergency: "6251 7666",
    publicHolidays: false,
    lat: 1.3731086,
    lng: 103.8298469,
    website: "https://www.mountpleasant.com.sg/locations/gelenggang/",
    instagram: "https://www.instagram.com/mountpleasantvetgroup",
  },
  {
    name: "Mount Pleasant Veterinary Centre (East)",
    block: "152",
    street: "EAST COAST ROAD",
    postalCode: "428855",
    openingHours:
      "Mon–Fri 9:30am–12:30pm, 2pm–4:30pm, 6pm–8:30pm · Sat–Sun 9:30am–12:30pm, 2pm–4:30pm",
    phone: "6348 6110",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.306334,
    lng: 103.9058262,
    website: "http://www.mpeast.com/",
    instagram: "https://www.instagram.com/mountpleasantvetgroup",
  },
  {
    name: "Mount Pleasant Veterinary Centre (Yishun)",
    block: "236",
    street: "YISHUN RING ROAD",
    floor: "1",
    unit: "1010",
    building: "YISHUN HEARTS",
    postalCode: "760236",
    openingHours:
      "Mon–Fri 9:30am–1pm, 2pm–7pm · Sat–Sun 9:30am–1pm, 2pm–5:30pm",
    phone: "6451 5242",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.4340676,
    lng: 103.838928,
    website: "https://www.mountpleasant.com.sg/locations/yishun/",
    instagram: "https://www.instagram.com/mountpleasantvetgroup",
  },
  {
    name: "My Animal Dispensary Pte Ltd",
    block: "1",
    street: "WEST COAST DRIVE",
    floor: "1",
    unit: "15",
    building: "NEWEST",
    postalCode: "128020",
    openingHours:
      "Mon–Tue 12pm–7pm · Wed Closed · Thu–Fri 12pm–7pm · Sat Closed · Sun 5pm–7pm",
    phone: "+65 6047 0177",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3157761,
    lng: 103.7578012,
    website: "https://www.myanimaldispensary.com/",
    instagram: "https://www.instagram.com/myanimaldispensary",
  },
  {
    name: "My Family Vet Clinic And Surgery Pte Ltd",
    block: "265",
    street: "BUKIT BATOK EAST AVENUE 4",
    floor: "1",
    unit: "403",
    postalCode: "650265",
    openingHours:
      "Mon 11am–9pm · Tue Closed · Wed–Fri 11am–9pm · Sat–Sun 11am–5pm",
    phone: "+65 8102 6966",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3501082,
    lng: 103.7599344,
    website: "https://myfamilyvetclinicandsurgery.com/",
    instagram: "https://www.instagram.com/myfamilyvet",
  },
  {
    name: "Nam Sang Veterinary Clinic Pte Ltd",
    block: "2",
    street: "BALESTIER ROAD",
    floor: "1",
    unit: "699",
    postalCode: "320002",
    openingHours:
      "Mon 10am–1pm · Tue 10am–7pm · Wed 10am–6pm · Thu 10am–7pm · Fri 10am–6pm · Sat 10am–7pm · Sun Closed",
    phone: "6254 8138",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3258546,
    lng: 103.8428618,
    website: "https://www.namsangvetclinic.com/",
  },
  {
    name: "Namly Veterinary Surgery Pte Ltd",
    block: "74",
    street: "NAMLY PLACE",
    building: "SHAMROCK PARK",
    postalCode: "267223",
    openingHours:
      "Mon–Fri 9:30am–12:30pm, 2pm–7pm · Sat–Sun 9:30am–12:30pm, 2pm–4:30pm",
    phone: "6469 4744",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3243247,
    lng: 103.7968316,
    website: "https://namlyvets.com.sg/",
    instagram: "https://www.instagram.com/namlyvetsurgery/",
  },
  {
    name: "Oasis Vet",
    block: "15",
    street: "VENUS ROAD",
    building: "WINDSOR PARK",
    postalCode: "574302",
    openingHours:
      "Mon–Fri 10am–12pm, 2pm–5pm, 6pm–8pm · Sat–Sun 10am–12pm, 2pm–5pm",
    phone: "+65 6256 2693",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3583604,
    lng: 103.8275554,
    website: "https://oasis-vet.com/",
    instagram: "https://www.instagram.com/oasisvetclinic/",
  },
  {
    name: "Ohana Vetcare",
    block: "258",
    street: "PASIR RIS STREET 21",
    floor: "4",
    unit: "1",
    postalCode: "510258",
    openingHours: "Mon–Sun 10am–12pm, 2pm–6pm, 7pm–9pm",
    phone: "6282 9070",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.366822,
    lng: 103.964534,
    website: "https://www.ohanavetcare.com.sg/",
    instagram: "https://www.instagram.com/ohanavetcare/",
  },
  {
    name: "Omnivet",
    block: "31",
    street: "JALAN MAS PUTEH",
    building: "PASIR PANJANG GARDENS",
    postalCode: "128633",
    openingHours: "",
    phone: "6887 0995",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3083597,
    lng: 103.7616849,
    website: "https://www.instagram.com/omnivet.sg/",
    instagram: "https://www.instagram.com/omnivet.sg/",
  },
  {
    name: "P.A.W (People Animal Wellness) Veterinary Centre Pte Ltd",
    block: "112",
    street: "BUKIT PURMEI ROAD",
    floor: "1",
    unit: "207",
    postalCode: "90112",
    openingHours: "Mon–Thu 10am–7pm · Fri–Sat 10am–5pm · Sun Closed",
    phone: "+65 6273 7573",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.2745295,
    lng: 103.8259281,
    website: "https://www.pawvetscentre.com/",
    instagram: "https://www.instagram.com/pawvets_sg/",
  },
  {
    name: "Passion Veterinary Clinic",
    block: "136",
    street: "MARSILING ROAD",
    floor: "1",
    unit: "2180",
    postalCode: "730136",
    openingHours: "Mon–Fri 10am–7pm · Sat–Sun 10am–5pm",
    phone: "6876 1522",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.4385606,
    lng: 103.7777298,
    website: "https://www.passionvet.com/",
    instagram: "https://www.instagram.com/passionvetsg/",
  },
  {
    name: "Passion Veterinary Clinic Pte Ltd",
    block: "111",
    street: "WOODLANDS STREET 13",
    floor: "1",
    unit: "86",
    postalCode: "730111",
    openingHours: "Mon–Fri 10am–7pm · Sat–Sun 10am–5pm",
    phone: "6876 1522",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.4379153,
    lng: 103.7820991,
    website: "https://www.passionvet.com/",
    instagram: "https://www.instagram.com/passionvetsg/",
  },
  {
    name: "Paws & Claws Veterinary Surgery",
    block: "285",
    street: "YISHUN AVENUE 6",
    floor: "1",
    unit: "6",
    building: "FICUS VALE",
    postalCode: "760285",
    openingHours: "Mon–Fri 10am–7pm · Sat–Sun 10am–6pm",
    phone: "6322 7913",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.4396399,
    lng: 103.8396141,
    website: "https://pawsnclawsvet.sg/",
    instagram: "https://www.instagram.com/pawsnclaws_vet",
  },
  {
    name: "Paws & Claws Veterinary Surgery",
    block: "6",
    street: "SIN MING ROAD",
    floor: "1",
    unit: "4",
    building: "SIN MING PLAZA",
    postalCode: "575585",
    openingHours: "Mon–Fri 10am–5pm, 6:30pm–11pm · Sat–Sun 7pm–11pm",
    phone: "6250 3375",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.352457,
    lng: 103.8357242,
    website: "https://pawsnclawsvet.sg/",
    instagram: "https://www.instagram.com/pawsnclaws_vet",
  },
  {
    name: "Pet Care Centre And Clinic Pte Ltd",
    block: "14",
    street: "WARINGIN PARK",
    building: "PET CARE CENTRE & CLINIC",
    postalCode: "416318",
    openingHours: "",
    phone: "",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3222328,
    lng: 103.9181562,
    website:
      "https://www.facebook.com/p/Pet-Care-Centre-Clinic-Pte-Ltd-100071892131975/",
  },
  {
    name: "Pet Clinic Pte Ltd",
    block: "211",
    street: "SERANGOON AVENUE 4",
    floor: "1",
    unit: "12",
    postalCode: "550211",
    openingHours: "",
    phone: "6288 5565",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3563813,
    lng: 103.8733905,
    website: "http://petclinic.sg/",
  },
  {
    name: "Pet Space (Singapore) Pte Ltd",
    block: "482",
    street: "SERANGOON ROAD",
    floor: "1",
    unit: "1",
    postalCode: "218149",
    openingHours: "Mon–Fri 10am–8pm · Sat–Sun 10am–6pm",
    phone: "+65 6252 2623",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3138435,
    lng: 103.8571935,
    website: "https://www.petspace.sg/",
    instagram: "https://www.instagram.com/petspace.sg/",
  },
  {
    name: "Pets Avenue Veterinary Clinic (Beauty World)",
    block: "50",
    street: "JALAN JURONG KECHIL",
    building: "JK BUILDING",
    postalCode: "598578",
    openingHours:
      "Mon–Fri 9am–12:30pm, 2pm–5pm, 6pm–9:30pm · Sat–Sun 9am–12:30pm, 2pm–5pm",
    phone: "6363 0333",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3405464,
    lng: 103.7742925,
    website: "https://www.petsavenuevet.com/contact-us/beauty-world",
    instagram: "https://www.instagram.com/petsavenuevet/",
  },
  {
    name: "Pets Avenue Veterinary Clinic (Farrer)",
    block: "8",
    street: "EMPRESS ROAD",
    floor: "1",
    unit: "11",
    building: "FARRER GARDENS",
    postalCode: "260008",
    openingHours:
      "Mon–Tue 9am–12:30pm, 2pm–5pm, 6pm–9:30pm · Wed 9am–12:30pm, 2pm–5pm · Thu–Fri 9am–12:30pm, 2pm–5pm, 6pm–9:30pm · Sat–Sun 9am–12:30pm, 2pm–5pm",
    phone: "6471 0111",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3167247,
    lng: 103.8061967,
    website: "https://www.petsavenuevet.com/contact-us/farrer-road",
    instagram: "https://www.instagram.com/petsavenuevet/",
  },
  {
    name: "Pets Avenue Veterinary Clinic (River Valley)",
    block: "241",
    street: "RIVER VALLEY ROAD",
    floor: "2",
    unit: "1",
    building: "GIANURN BUILDING",
    postalCode: "238298",
    openingHours: "Mon–Sun 9am–12:30pm, 2pm–5pm, 6pm–12am",
    phone: "6993 0333",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.2942137,
    lng: 103.8418545,
    website: "https://www.petsavenuevet.com/contact-us/river-valley",
    instagram: "https://www.instagram.com/petsavenuevet/",
  },
  {
    name: "Pets Avenue Veterinary Clinic (Upper Thomson)",
    block: "193",
    street: "UPPER THOMSON ROAD",
    building: "YEW LIAN PARK",
    postalCode: "574338",
    openingHours:
      "Mon–Fri 9am–12:30pm, 2pm–5pm, 6pm–9:30pm · Sat–Sun 9am–12:30pm, 2pm–5pm",
    phone: "6259 0555",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3517091,
    lng: 103.8352688,
    website: "https://www.petsavenuevet.com/",
    instagram: "https://www.instagram.com/petsavenuevet/",
  },
  {
    name: "Pets Avenue Veterinary Clinic And Referrals",
    block: "328",
    street: "CHANGI ROAD",
    floor: "1",
    unit: "1",
    building: "TEDGE",
    postalCode: "419803",
    openingHours:
      "Mon–Fri 9am–12:30pm, 2pm–5pm, 6pm–9:30pm · Sat 9am–12:30pm, 2pm–5pm · Sun Closed",
    phone: "6910 0555",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3182036,
    lng: 103.9088271,
    website: "https://www.pavcarvets.com/",
    instagram: "https://www.instagram.com/pavcar.vets/",
  },
  {
    name: "Point Veterinary Surgery",
    block: "541",
    street: "JURONG WEST AVENUE 1",
    floor: "1",
    unit: "1044",
    postalCode: "640541",
    openingHours: "",
    phone: "",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.35122,
    lng: 103.7160219,
    website: "http://www.pointveterinarysurgery.com/",
  },
  {
    name: "Rehabvet Clinic",
    block: "513",
    street: "SERANGOON ROAD",
    floor: "1",
    unit: "1",
    postalCode: "218154",
    openingHours:
      "Mon–Wed 11am–8pm · Thu 9am–6pm · Fri 11am–8pm · Sat–Sun 10am–6pm",
    phone: "+65 6291 6881 / +65 8798 7554",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.314668,
    lng: 103.857401,
    website: "https://rehabvet.com/",
    instagram: "https://www.instagram.com/rehabvet_sg/",
  },
  {
    name: "Singapore Turf Club Equine Hospital",
    block: "1",
    street: "TURF CLUB AVENUE",
    postalCode: "738078",
    openingHours: "",
    phone: "6879 1000",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.4219631,
    lng: 103.7623626,
    website: "https://racing.turfclub.com.sg/en/veterinary/",
  },
  {
    name: "Singapore Veterinary (Singvet) Animal Clinic Beauty World",
    block: "66",
    street: "JALAN JURONG KECHIL",
    building: "JK BUILDING",
    postalCode: "598586",
    openingHours: "Mon–Fri 9am–9pm · Sat–Sun 9am–6pm",
    phone: "6859 3860",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3405144,
    lng: 103.7739725,
    website: "https://singvet.sg/",
    instagram: "https://www.instagram.com/singvet.sg/",
  },
  {
    name: "Singapore Veterinary (Singvet) Animal Clinic Pte Ltd",
    block: "768",
    street: "WOODLANDS AVENUE 6",
    floor: "1",
    unit: "11",
    building: "WOODLANDS MART",
    postalCode: "730768",
    openingHours:
      "Mon 9am–9pm · Tue 9am–6pm · Wed 9am–9pm · Thu 9am–6pm · Fri–Sat 9am–9pm · Sun 9am–6pm",
    phone: "6365 0308",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.4454883,
    lng: 103.79799,
    website: "https://singvet.sg/",
    instagram: "https://www.instagram.com/singvet.sg/",
  },
  {
    name: "Sora Vet",
    block: "37",
    street: "CHAI CHEE AVENUE",
    floor: "1",
    unit: "291",
    building: "ANSAR GARDEN",
    postalCode: "461037",
    openingHours: "",
    phone: "",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3254606,
    lng: 103.9264806,
    instagram: "https://www.instagram.com/soravet_sg",
  },
  {
    name: "Spca Community Animal Clinic",
    block: "50",
    street: "SUNGEI TENGAH ROAD",
    floor: "1",
    unit: "1",
    postalCode: "699012",
    openingHours: "Mon–Wed 11am–4pm · Thu Closed · Fri–Sun 11am–4pm",
    phone: "6287 5355 (ext 14)",
    area: "",
    emergency: "6287 5355 (ext 9)",
    publicHolidays: true,
    lat: 1.3807208,
    lng: 103.7320055,
    website: "https://spca.org.sg/services/community-animal-clinic/",
    instagram: "https://www.instagram.com/spcasingapore/",
  },
  {
    name: "Spring Veterinary Care",
    block: "123",
    street: "HOUGANG AVENUE 1",
    floor: "1",
    unit: "1412",
    postalCode: "530123",
    openingHours: "Mon–Sat 10:30am–2:30pm, 3:30pm–8:30pm · Sun 10:30am–5:30pm",
    phone: "6286 3313",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3533489,
    lng: 103.8862543,
    website: "https://www.springvet.com.sg/",
    instagram: "https://www.instagram.com/springveterinarycare/",
  },
  {
    name: "Spring Veterinary Care Punggol",
    block: "681",
    street: "PUNGGOL DRIVE",
    floor: "1",
    unit: "16A",
    postalCode: "820681",
    openingHours: "Mon–Sat 10:30am–2:30pm, 3:30pm–8:30pm · Sun 10:30am–5:30pm",
    phone: "6244 1469",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.4031154,
    lng: 103.9132209,
    website: "https://www.springvet.com.sg/",
    instagram: "https://www.instagram.com/springveterinarycare/",
  },
  {
    name: "Stars Veterinary Clinic (Hougang Village)",
    block: "681",
    street: "HOUGANG AVENUE 8",
    floor: "1",
    unit: "841",
    postalCode: "530681",
    openingHours: "Mon Closed · Tue–Fri 9am–6pm · Sat Closed · Sun 9am–6pm",
    phone: "+65 6203 2282",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3727416,
    lng: 103.8859111,
    website: "http://starsveterinaryclinic.com/",
  },
  {
    name: "Stars Veterinary Clinic Pte Ltd",
    block: "211",
    street: "HOUGANG STREET 21",
    floor: "1",
    unit: "301",
    postalCode: "530211",
    openingHours: "Mon–Sun 9:30am–9:30pm",
    phone: "+65 6280 9880",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3593039,
    lng: 103.8876514,
    website: "http://starsveterinaryclinic.com/",
  },
  {
    name: "The Animal Clinic",
    block: "109",
    street: "CLEMENTI STREET 11",
    floor: "1",
    unit: "19",
    postalCode: "120109",
    openingHours:
      "Mon 9am–12:30pm, 2pm–5pm, 6pm–8:30pm · Tue 9am–12:30pm, 2pm–5pm · Wed 9am–12:30pm, 2pm–5pm, 6pm–8:30pm · Thu 9am–12:30pm, 2pm–5pm · Fri 9am–12:30pm, 2pm–5pm, 6pm–8:30pm · Sat 9am–1pm, 2pm–5pm · Sun Closed",
    phone: "6776 3450 / 6777 0273",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3222655,
    lng: 103.770609,
    website: "https://www.animalclinic.com.sg/",
  },
  {
    name: "The Animal Clinic (Katong Branch)",
    block: "55",
    street: "LORONG L TELOK KURAU",
    floor: "1",
    unit: "63",
    building: "BRIGHT CENTRE",
    postalCode: "425500",
    openingHours:
      "Mon–Tue 9am–12:30pm, 2pm–7:30pm · Wed Closed · Thu–Fri 9am–12:30pm, 2pm–7:30pm · Sat 9am–12:30pm, 2pm–5pm · Sun Closed",
    phone: "6440 4767 / 6440 2336",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3117874,
    lng: 103.9106252,
    website: "https://www.animalclinic.com.sg/",
  },
  {
    name: "The Animal Doctors",
    block: "108",
    street: "ANG MO KIO AVENUE 4",
    floor: "1",
    unit: "96",
    building: "KEBUN BARU HEIGHTS",
    postalCode: "560108",
    openingHours: "Mon–Fri 10am–1pm, 3pm–8pm · Sat–Sun 11am–5pm",
    phone: "6451 4531",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3710589,
    lng: 103.8378599,
    website: "https://www.theanimaldoctors.com.sg/",
  },
  {
    name: "The Animal Doctors (Tiong Bahru)",
    block: "11A",
    street: "BOON TIONG ROAD",
    floor: "2",
    unit: "7",
    building: "TIONG BAHRU VIEW",
    postalCode: "161011",
    openingHours:
      "Mon–Tue 9:30am–8:30pm · Wed Closed · Thu–Fri 9:30am–8:30pm · Sat–Sun 9:30am–1:30pm",
    phone: "6253 3023",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.2862033,
    lng: 103.8291812,
    website: "https://www.theanimaldoctors.com.sg/",
  },
  {
    name: "The Cat Vet",
    block: "2",
    street: "PANDAN VALLEY",
    floor: "B1",
    unit: "204D",
    building: "ACACIA COURT",
    postalCode: "597626",
    openingHours:
      "Mon 10am–12pm, 2pm–7pm · Tue–Wed 10am–12pm, 2pm–6pm · Thu Closed · Fri 10am–12pm, 2pm–7pm · Sat 10am–12pm, 2pm–5pm · Sun Closed",
    phone: "+65 6363 2272",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3193006,
    lng: 103.7788849,
    website: "https://thecatvet.sg/",
    instagram: "https://www.instagram.com/thecatvet.sg/",
  },
  {
    name: "The Eye Specialist For Animals",
    block: "299",
    street: "TANJONG KATONG ROAD",
    postalCode: "437082",
    openingHours: "",
    phone: "+65 6241 2011",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3064345,
    lng: 103.8959501,
    website: "https://eyespecialistforanimals.com/",
    instagram: "https://www.instagram.com/singaporeeyevet/",
  },
  {
    name: "The Gentle Vet",
    block: "291",
    street: "TANJONG KATONG ROAD",
    postalCode: "437074",
    openingHours:
      "Mon–Fri 9:30am–1pm, 2:30pm–5pm, 6pm–8pm · Sat–Sun 9:30am–1pm, 2:30pm–6pm",
    phone: "6655 3970",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3066556,
    lng: 103.8958784,
    website: "https://thegentlevet.sg/",
    instagram: "https://www.instagram.com/gentlevet.sg/",
  },
  {
    name: "The Joyous Vet Pte Ltd",
    block: "475",
    street: "CHOA CHU KANG AVENUE 3",
    floor: "1",
    unit: "30A",
    postalCode: "680475",
    openingHours: "Mon–Sun 1pm–5pm, 6:30pm–9pm",
    phone: "6769 0304",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3780266,
    lng: 103.7389881,
    website: "http://www.tjv.com.sg/",
  },
  {
    name: "The Pet Physician",
    block: "2",
    street: "JALAN PARI BURONG",
    building: "PICARDY GARDENS",
    postalCode: "488668",
    openingHours: "Mon–Fri 9:30am–8pm · Sat–Sun 9:30am–6pm",
    phone: "6970 5267",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.333945,
    lng: 103.948884,
    website: "https://www.thepetphysician.com.sg/",
    instagram: "https://www.instagram.com/thepetphysiciansg/",
  },
  {
    name: "The Vet Ward",
    block: "112",
    street: "LAVENDER STREET",
    floor: "1",
    unit: "1",
    building: "CHANG HUA BUILDING",
    postalCode: "338728",
    openingHours: "Mon–Fri 9am–7pm · Sat–Sun 9am–5pm",
    phone: "6358 2663",
    area: "",
    emergency: "",
    publicHolidays: true,
    lat: 1.3112556,
    lng: 103.8628366,
    website: "https://thevetward.com/",
  },
  {
    name: "The Veterinary Clinic",
    block: "31",
    street: "LORONG LIPUT",
    building: "HOLLAND VILLAGE",
    postalCode: "277742",
    openingHours: "Mon–Sat 10am–7pm · Sun Closed",
    phone: "6468 6312",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3106843,
    lng: 103.7949565,
    website: "http://vetclinic.sg/",
    instagram: "https://www.instagram.com/vetclinicsg/",
  },
  {
    name: "The Veterinary Clinic @ Tampines Pte Ltd",
    block: "476",
    street: "TAMPINES STREET 44",
    floor: "1",
    unit: "201",
    postalCode: "520476",
    openingHours: "Mon–Sat 10am–7pm · Sun Closed",
    phone: "6784 2048",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3609703,
    lng: 103.9533971,
    website: "http://vetclinic.sg/",
    instagram: "https://www.instagram.com/vetclinicsg/",
  },
  {
    name: "The Visiting Vets Clinic",
    block: "9",
    street: "TAMAN SERASI",
    floor: "1",
    unit: "9",
    postalCode: "257720",
    openingHours: "Mon–Sat 10am–7pm · Sun Closed",
    phone: "6475 3405",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3084941,
    lng: 103.8191233,
    website: "https://thevisitingvets.com.sg/",
  },
  {
    name: "Toa Payoh Vets Pte Ltd",
    block: "1002",
    street: "TOA PAYOH INDUSTRIAL PARK",
    floor: "1",
    unit: "1477",
    postalCode: "319074",
    openingHours: "Mon–Fri 10am–7pm · Sat–Sun 10am–4pm",
    phone: "6254 3326",
    area: "",
    emergency: "",
    publicHolidays: true,
    lat: 1.335942,
    lng: 103.861019,
    website: "https://www.toapayohvets.com/",
    instagram: "https://www.instagram.com/toapayohvets",
  },
  {
    name: "Town Vets Animal Clinic Pte Ltd",
    block: "22",
    street: "HAVELOCK ROAD",
    floor: "1",
    unit: "687",
    postalCode: "160022",
    openingHours: "Mon–Fri 9:30am–8:30pm · Sat 9:30am–5pm · Sun Closed",
    phone: "6276 7026",
    area: "",
    emergency: "6266 0232",
    publicHolidays: false,
    lat: 1.2887624,
    lng: 103.8289483,
    website: "https://www.townvets.com.sg/",
  },
  {
    name: "Tp Animal Clinic & Wellness Centre",
    block: "21",
    street: "TAMPINES AVENUE 1",
    building: "TEMASEK POLYTECHNIC",
    postalCode: "529757",
    openingHours: "Mon, Wed–Fri 9am–5pm · Tue Closed · Sat–Sun Closed",
    phone: "6780 6969",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.345315,
    lng: 103.931822,
    website:
      "https://www.tp.edu.sg/research-and-industry/centres-of-excellence/centres-under-school-of-applied-science/tp-animal-clinic-wellness-tpacw.html",
  },
  {
    name: "United Veterinary Clinic Pte Ltd",
    block: "107",
    street: "ANG MO KIO AVENUE 4",
    floor: "1",
    unit: "148",
    building: "KEBUN BARU HEIGHTS",
    postalCode: "560107",
    openingHours: "Mon–Sun 9am–9pm",
    phone: "6455 6880",
    area: "",
    emergency: "",
    publicHolidays: true,
    lat: 1.3714168,
    lng: 103.8372427,
    website: "https://www.unitedvetclinic.com/",
    instagram: "https://www.instagram.com/unitedvets",
  },
  {
    name: "Ves Hospital",
    block: "232",
    street: "WHITLEY ROAD",
    building: "MOUNT PLEASANT ANIMAL HOSPITAL",
    postalCode: "297824",
    openingHours: "",
    phone: "6266 0232",
    area: "",
    emergency: "6266 0232",
    publicHolidays: false,
    lat: 1.3256514,
    lng: 103.8272562,
    website: "https://www.veshospital.com.sg/",
    instagram: "https://www.instagram.com/VESHospital",
  },
  {
    name: "Vet Affinity Pte Ltd",
    block: "151",
    street: "BUKIT BATOK STREET 11",
    floor: "1",
    unit: "248",
    postalCode: "650151",
    openingHours: "Mon–Sat 9am–8pm · Sun Closed",
    phone: "6970 7505",
    area: "",
    emergency: "Westside Emergency 6931 0095 / Pet A&E 6463 7228",
    publicHolidays: false,
    lat: 1.3487581,
    lng: 103.7442612,
    website: "https://www.vetaffinity.com.sg/",
    instagram: "https://www.instagram.com/vetaffinity",
  },
  {
    name: "Vet Central",
    block: "69",
    street: "LORONG 4 TOA PAYOH",
    building: "TOA PAYOH VISTA",
    postalCode: "310069",
    openingHours: "Mon–Sat 9am–7pm · Sun Closed",
    phone: "6635 8646",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3341946,
    lng: 103.8527221,
    website: "https://vetcentral.com.sg/",
    instagram: "https://www.instagram.com/vetcentralsingapore/",
  },
  {
    name: "Vet Central (Swan Lake) Pte Ltd",
    block: "19",
    street: "SWAN LAKE AVENUE",
    building: "OPERA ESTATE",
    postalCode: "455708",
    openingHours: "Mon–Sat 9am–1pm, 3pm–7pm · Sun Closed",
    phone: "6346 8646",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3213401,
    lng: 103.9240904,
    website: "https://vetcentral.com.sg/",
    instagram: "https://www.instagram.com/vetcentralsingapore/",
  },
  {
    name: "Vet Practice Pte Ltd",
    block: "31",
    street: "HOLLAND CLOSE",
    floor: "1",
    unit: "219",
    postalCode: "270031",
    openingHours:
      "Mon–Tue 9am–12pm, 2pm–5pm, 6pm–8:30pm · Wed 9am–1pm · Thu–Sat 9am–12pm, 2pm–5pm, 6pm–8:30pm · Sun 9am–1pm",
    phone: "6778 5285 / 6778 5286",
    area: "",
    emergency: "9640 3564",
    publicHolidays: false,
    lat: 1.3067869,
    lng: 103.7972855,
    website: "https://vetpractice.com.sg/",
    instagram: "https://www.instagram.com/vetpracticesg/",
  },
  {
    name: "Vet Practice Pte Ltd",
    block: "21",
    street: "LORONG KILAT",
    floor: "1",
    unit: "4",
    building: "SUN COURT",
    postalCode: "598123",
    openingHours: "Mon–Sat 9am–12pm, 2pm–5pm, 6pm–8:30pm · Sun 9am–1pm",
    phone: "6462 1757 / 6462 1541",
    area: "",
    emergency: "9640 3564",
    publicHolidays: false,
    lat: 1.340877,
    lng: 103.7730952,
    website: "https://vetpractice.com.sg/",
    instagram: "https://www.instagram.com/vetpracticesg/",
  },
  {
    name: "Vetmedic Animal Clinic And Surgery",
    block: "52",
    street: "JALAN MALU-MALU",
    building: "SEMBAWANG SPRINGS ESTATE",
    postalCode: "769667",
    openingHours: "Mon–Fri 9:30am–1pm, 2pm–8pm · Sat–Sun 9:30am–5pm",
    phone: "+65 6015 0393",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.4435911,
    lng: 103.8258374,
    website: "https://www.vetmedic.com.sg/",
  },
  {
    name: "Vets For Life Animal Clinic",
    block: "27A",
    street: "LORONG LIPUT",
    building: "HOLLAND VILLAGE",
    postalCode: "277738",
    openingHours:
      "Mon–Fri 9:30am–12:30pm, 2pm–5pm, 6pm–8pm · Sat–Sun 9:30am–1pm, 2pm–5:30pm",
    phone: "+65 6970 7070",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3104999,
    lng: 103.7948243,
    website: "https://www.vetsforlife.com.sg/",
    instagram: "https://www.instagram.com/vetsforlifesg/",
  },
  {
    name: "Vets For Life Animal Clinic",
    block: "330",
    street: "TANJONG KATONG ROAD",
    postalCode: "437106",
    openingHours:
      "Mon–Fri 9:30am–12:30pm, 2pm–5pm, 6pm–10:30pm · Sat–Sun 9:30am–1pm, 2pm–5:30pm",
    phone: "+65 6348 8346",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3041715,
    lng: 103.8963416,
    website: "https://www.vetsforlife.com.sg/",
    instagram: "https://www.instagram.com/vetsforlifesg/",
  },
  {
    name: "Vets For Life Animal Clinic Pte Ltd",
    block: "491",
    street: "RIVER VALLEY ROAD",
    floor: "1",
    unit: "5",
    postalCode: "248371",
    openingHours:
      "Mon–Fri 9:30am–12:30pm, 2pm–5pm, 6pm–8pm · Sat–Sun 9:30am–1pm, 2pm–5:30pm",
    phone: "+65 6732 0273",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.2931322,
    lng: 103.8268791,
    website: "https://www.vetsforlife.com.sg/",
    instagram: "https://www.instagram.com/vetsforlifesg/",
  },
  {
    name: "Vets For Pets (Lengkok Bahru)",
    block: "57",
    street: "LENGKOK BAHRU",
    floor: "1",
    unit: "475",
    postalCode: "151057",
    openingHours:
      "Mon Closed · Tue 10am–12pm, 2:30pm–6pm · Wed–Thu Closed · Fri–Sat 10am–12pm, 2:30pm–6pm · Sun Closed",
    phone: "6255 6064",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.2882665,
    lng: 103.8141523,
    website: "https://www.vetsforpetsclinic.com/",
    instagram: "https://www.instagram.com/excuseme_drwang",
  },
  {
    name: "Vets For Pets Pte Ltd",
    block: "519",
    street: "JURONG WEST STREET 52",
    floor: "1",
    unit: "157",
    postalCode: "640519",
    openingHours:
      "Mon–Fri 10am–12pm, 2:30pm–8pm · Sat 10am–12pm, 2pm–5pm · Sun 12pm–4pm",
    phone: "6569 1627",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.345555,
    lng: 103.7175918,
    website: "https://www.vetsforpetsclinic.com/",
    instagram: "https://www.instagram.com/excuseme_drwang",
  },
  {
    name: "West Coast Vetcare Pte Ltd",
    block: "612",
    street: "CLEMENTI WEST STREET 1",
    floor: "1",
    unit: "300",
    postalCode: "120612",
    openingHours: "Mon–Fri 10am–12pm, 2pm–7pm · Sat–Sun 10am–12pm, 2pm–5pm",
    phone: "+65 6777 7423",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.3035239,
    lng: 103.7686841,
    website: "https://www.westcoastvetcare.com/",
    instagram: "https://www.instagram.com/westcoastvetcare/",
  },
  {
    name: "Westwide Veterinary Emergency And Referral Hospital",
    block: "86",
    street: "SERANGOON GARDEN WAY",
    building: "SERANGOON GARDEN ESTATE",
    postalCode: "555982",
    openingHours: "Mon–Sun 24 hours",
    phone: "6931 0095",
    area: "",
    emergency: "6931 0095",
    publicHolidays: true,
    lat: 1.3639688,
    lng: 103.8658082,
    website: "https://www.westsideemergency.com.sg/",
    instagram: "https://www.instagram.com/westside.emergency/",
  },
  {
    name: "Woodgrove Veterinary Services Pte Ltd",
    block: "10",
    street: "WOODLANDS SQUARE",
    floor: "1",
    unit: "41",
    building: "WOODS SQUARE",
    postalCode: "737714",
    openingHours: "Mon Closed · Tue–Sat 9am–1pm, 2pm–6pm · Sun 9am–1pm",
    phone: "+65 6038 0490",
    area: "",
    emergency: "",
    publicHolidays: false,
    lat: 1.4348773,
    lng: 103.7847314,
    website: "https://wvets.com.sg/",
  },
];

const NAMES = [
  "Buddy",
  "Bella",
  "Charlie",
  "Luna",
  "Max",
  "Daisy",
  "Milo",
  "Ruby",
  "Cooper",
  "Lola",
];
const GENDERS = ["Male", "Female"] as const;

export const seedDogs = internalMutation({
  args: { count: v.number() },
  handler: async (ctx, args) => {
    // 1. Get existing welfare groups to link them
    const groups = await ctx.db.query("welfareGroups").collect();
    if (groups.length === 0) {
      throw new Error(
        "Please add at least one Welfare Group before seeding dogs.",
      );
    }

    for (let i = 0; i < args.count; i++) {
      const randomGroup = groups[Math.floor(Math.random() * groups.length)];
      const randomGender = GENDERS[Math.floor(Math.random() * GENDERS.length)];

      // Generate a random birthday between 1 and 10 years ago
      const yearsAgo = Math.floor(Math.random() * 10) + 1;
      const birthday = new Date();
      birthday.setFullYear(birthday.getFullYear() - yearsAgo);

      await ctx.db.insert("dogs", {
        name: `${NAMES[Math.floor(Math.random() * NAMES.length)]} ${i + 1}`,
        gender: randomGender,
        birthday: birthday.toISOString(),
        hdbApproved: Math.random() > 0.5 ? "Yes" : "No",
        welfareGroupId: randomGroup._id,
        status: "Active",
        // Using a placeholder image from your logic
        imageStorageId: undefined,
        description:
          "This is a generated dog description for testing purposes.",
      });
    }

    return `Successfully seeded ${args.count} dogs!`;
  },
});

const WELFARE_GROUPS = [
  {
    name: "SOSD — Save Our Street Dogs",
    blurb: "Singapore Specials. Sanctuary in Jalan Bahar.",
    dogsAvailable: 86,
    website: "https://sosd.org.sg",
    facebook: "https://facebook.com/sosd.sg",
    instagram: "https://instagram.com/sosd_sg",
    tiktok: "https://tiktok.com/@sosd.sg",
    youtube: "https://youtube.com/@sosdsingapore",
  },
  {
    name: "Action for Singapore Dogs",
    blurb: "Rescue, rehab, rehome. Since 2000.",
    dogsAvailable: 52,
    website: "https://asdsingapore.com",
    facebook: "https://facebook.com/ActionForSingaporeDogs",
    instagram: "https://instagram.com/asd_singapore",
  },
  {
    name: "Causes for Animals (Singapore)",
    blurb: "Community cats & rescue dogs.",
    dogsAvailable: 34,
    website: "https://causesforanimals.com",
    facebook: "https://facebook.com/CausesForAnimalsSG",
    instagram: "https://instagram.com/causesforanimals",
    youtube: "https://youtube.com/@causesforanimals",
  },
  {
    name: "Voices for Animals",
    blurb: "Senior dogs & long-stayers.",
    dogsAvailable: 41,
    website: "https://voicesforanimals.com.sg",
    facebook: "https://facebook.com/voicesforanimalssg",
    instagram: "https://instagram.com/voicesforanimalssg",
    tiktok: "https://tiktok.com/@voicesforanimals",
  },
  {
    name: "OSCAS — Oasis Second Chance",
    blurb: "Farmway shelter in Sungei Tengah.",
    dogsAvailable: 63,
    website: "https://oscas.com.sg",
    facebook: "https://facebook.com/oscas.sg",
    instagram: "https://instagram.com/oscas_sg",
  },
  {
    name: "Exclusively Mongrels Ltd",
    blurb: "Local mongrels only. Foster-first.",
    dogsAvailable: 28,
    website: "https://exclusivelymongrels.org",
    facebook: "https://facebook.com/exclusivelymongrels",
    instagram: "https://instagram.com/exclusivelymongrels",
  },
  {
    name: "Mercylight Animal Sanctuary",
    blurb: "Senior & special-needs animals.",
    dogsAvailable: 47,
    website: "https://mercylight.sg",
    facebook: "https://facebook.com/MercylightSanctuary",
    instagram: "https://instagram.com/mercylightsanctuary",
    youtube: "https://youtube.com/@mercylight",
  },
  {
    name: "Purely Adoptions",
    blurb: "Adopt-don't-shop advocacy.",
    dogsAvailable: 19,
    website: "https://purelyadoptions.com",
    facebook: "https://facebook.com/purelyadoptions",
    instagram: "https://instagram.com/purelyadoptions",
    tiktok: "https://tiktok.com/@purelyadoptions",
  },
  {
    name: "Animal Lovers League",
    blurb: "Cage-free farmway shelter.",
    dogsAvailable: 71,
    website: "https://animalloversleague.com",
    facebook: "https://facebook.com/AnimalLoversLeague",
    instagram: "https://instagram.com/animalloversleague",
  },
  {
    name: "SPCA Singapore",
    blurb: "Adoption, inspection, advocacy.",
    dogsAvailable: 38,
    website: "https://spca.org.sg",
    facebook: "https://facebook.com/spca.singapore",
    instagram: "https://instagram.com/spcasingapore",
    tiktok: "https://tiktok.com/@spcasingapore",
    youtube: "https://youtube.com/@SPCASingapore",
  },
];

export const seedWelfareGroups = internalMutation({
  handler: async (ctx) => {
    const existing = await ctx.db.query("welfareGroups").collect();
    if (existing.length > 0) return "Welfare groups already seeded.";
    for (const g of WELFARE_GROUPS) {
      const slug = g.name
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-|-$/g, "");
      await ctx.db.insert("welfareGroups", { ...g, slug, status: "Active" });
    }
    return `Seeded ${WELFARE_GROUPS.length} welfare groups.`;
  },
});

const EVENTS = [
  {
    name: "Spring Adoption Drive",
    kind: "Adoption",
    image: "https://placedog.net/1200/600?id=200",
    location: "Bishan Park Pavilion, Hall A",
    dateTime: "5 Apr 2026 to 6 Apr 2026, 8am to 9pm daily",
    short:
      "Meet 30+ rescue dogs over one weekend. On-site adoption counsellors, free goodie bags, and a quiet room for shy doggos to mingle slowly with prospective families.",
    tag: "Featured",
  },
  {
    name: "Homeward Annual Pet Fair",
    kind: "Pet Fair",
    image: "https://placedog.net/1200/600?id=210",
    location: "Suntec Convention Hall 401",
    dateTime: "17 May 2026, 10am to 7pm",
    short:
      "Our biggest day of the year. 40+ small businesses, vet talks, training demos, paw-print art for the kids, and a live shelter dog showcase every hour on the hour.",
  },
  {
    name: "Microchip & Vaccination Day",
    kind: "Clinic",
    image: "https://placedog.net/1200/600?id=220",
    location: "Mt Pleasant Vet, Whitley Road",
    dateTime: "22 Jun 2026, 9am to 1pm",
    short:
      "Subsidised microchipping ($15) and core vaccinations ($40) for adopted dogs and Singapore Specials. By appointment — limited to 60 slots.",
  },
  {
    name: "Sunset Sembawang Walk",
    kind: "Community",
    image: "https://placedog.net/1200/600?id=230",
    location: "Sembawang Park Boardwalk",
    dateTime: "12 Jul 2026, 5pm to 7pm",
    short:
      "A monthly community walk for adopters, fosters and curious dog-lovers. Bring water, bring your dog, bring a friend who's been thinking about adopting.",
  },
  {
    name: "Senior Dogs Meet & Greet",
    kind: "Adoption",
    image: "https://placedog.net/1200/600?id=240",
    location: "Homeward Shelter, Sembawang",
    dateTime: "3 Aug 2026 to 4 Aug 2026, 11am to 5pm daily",
    short:
      "Eight of our older residents need quiet homes for their best years yet. Drop by for a slow afternoon, a cup of tea, and the company of a very good old dog.",
  },
  {
    name: "Foster Carer Workshop",
    kind: "Training",
    image: "https://placedog.net/1200/600?id=250",
    location: "Homeward Shelter, Sembawang",
    dateTime: "14 Sep 2026, 2pm to 5pm",
    short:
      "Considering becoming a foster carer? Spend an afternoon with our team learning the basics — feeding, decompression, vet visits, and how to say goodbye.",
  },
];

export const seedEvents = internalMutation({
  handler: async (ctx) => {
    const existing = await ctx.db.query("events").collect();
    if (existing.length > 0) return "Events already seeded.";
    for (const ev of EVENTS) {
      await ctx.db.insert("events", ev);
    }
    return `Seeded ${EVENTS.length} events.`;
  },
});

export const seedVets = internalMutation({
  handler: async (ctx) => {
    const existing = await ctx.db.query("vets").collect();
    if (existing.length > 0) return "Vets already seeded.";
    for (const vet of VETS) {
      await ctx.db.insert("vets", vet);
    }
    return `Seeded ${VETS.length} vets.`;
  },
});

const SERVICES = [
  {
    name: "Paws & Pencils Studio",
    category: "Artists",
    blurb:
      "Hand-drawn graphite portraits and full-colour pastel commissions of your dog. Two-week turnaround, ships in a tube.",
    address: " Tiong Bahru",
    priceFrom: "$120",
    website: "https://pawsandpencils.sg",
    phone: "+65 9123 4567",
  },
  {
    name: "Tiny Snout Watercolours",
    category: "Artists",
    blurb:
      "Loose, joyful watercolour portraits by Bukit Timah-based illustrator Lin Wei. Originals come in A5 to A3.",
    address: " Bukit Timah",
    priceFrom: "$85",
    website: "https://tinysnout.studio",
  },
  {
    name: "Forever Paws — Clay Casting",
    category: "Artists",
    blurb:
      "Memorial paw-print clay impressions and 3D-printed scans. Often booked for end-of-life keepsakes.",
    address: " Geylang",
    priceFrom: "$60",
    website: "https://foreverpaws.sg",
    phone: "+65 8234 9921",
  },
  {
    name: "Mobile Aftercare Services",
    category: "Cremation",
    blurb:
      "Compassionate individual cremation with home pick-up. Family viewings available; ashes returned in a hand-finished urn.",
    address: " Mandai (collection)",
    priceFrom: "$280",
    website: "https://mobileaftercare.sg",
    phone: "+65 6452 0500",
  },
  {
    name: "Pets Cremation Services SG",
    category: "Cremation",
    blurb:
      "Group and private cremation, scatter garden, paw-print impression service. Open daily including public holidays.",
    address: " Ulu Pandan",
    priceFrom: "$220",
    website: "https://petscremation.sg",
    phone: "+65 8101 8101",
  },
  {
    name: "The Pet Memorial Park",
    category: "Cremation",
    blurb:
      "Memorial niches, annual remembrance day, and grief-support volunteers for families saying goodbye.",
    address: " Mandai",
    priceFrom: "$450",
    website: "https://petmemorial.sg",
  },
  {
    name: "Pawfect Provisions",
    category: "Pet shops",
    blurb:
      "Independent shop carrying air-dried kibble, raw meals, and SG-made enrichment toys. Free delivery above $80.",
    address: " Joo Chiat",
    website: "https://pawfectprovisions.sg",
    phone: "+65 6440 1188",
  },
  {
    name: "The Tail Wag Shoppe",
    category: "Pet shops",
    blurb:
      "Small but mighty — local brands, single-protein treats and harnesses fitted in-store by ex-vet-nurse Mei.",
    address: " Tiong Bahru",
    website: "https://tailwagshoppe.sg",
    phone: "+65 6555 2099",
  },
  {
    name: "Kibble & Co.",
    category: "Pet shops",
    blurb:
      "Subscription kibble (rotational proteins, freshly milled), cold-pressed treats, and the friendliest counter staff in town.",
    address: " Holland Village",
    priceFrom: "$32/mo",
    website: "https://kibbleco.sg",
  },
  {
    name: "PawFresh Meals",
    category: "Small businesses",
    blurb:
      "Gently cooked fresh meals delivered weekly across the island. Vet-formulated; bowls portioned by your dog's weight.",
    address: " Islandwide delivery",
    priceFrom: "$18/wk",
    website: "https://pawfresh.sg",
    phone: "+65 8800 4733",
  },
  {
    name: "Bone Appétit Bakery",
    category: "Small businesses",
    blurb:
      "Birthday cakes, peanut-butter pupcakes, and biscuit tins decorated with your dog's name in soft icing.",
    address: " East Coast",
    priceFrom: "$28",
    website: "https://boneappetit.sg",
  },
  {
    name: "Wagtail Apothecary",
    category: "Small businesses",
    blurb:
      "SG-made shampoos, paw balms, and calming sprays in refillable amber bottles. Small-batch, fragrance-light.",
    address: " Jurong East",
    priceFrom: "$14",
    website: "https://wagtailapothecary.sg",
  },
  {
    name: "Quiet Conversations — Lina Toh",
    category: "Animal communication",
    blurb:
      "Intuitive sessions for behaviour issues, transitions, and end-of-life care. Sessions over video or in-person.",
    address: " Online & home visits",
    priceFrom: "$160/session",
    website: "https://quietconversations.sg",
  },
  {
    name: "Heart-to-Heart Animal Talk",
    category: "Animal communication",
    blurb:
      "By Joanna Chan, certified by the Animal Spirit Network. Specialises in newly-adopted shelter dogs settling in.",
    address: " Online",
    priceFrom: "$120/session",
    website: "https://heart2heart.sg",
  },
  {
    name: "Fresh Paws Laundromat",
    category: "Pet laundromats",
    blurb:
      "Dedicated machines for pet bedding, harnesses, and cooling mats. Hot-rinse cycle for tick & flea removal.",
    address: " Bedok",
    priceFrom: "$8/load",
    website: "https://freshpaws.sg",
  },
  {
    name: "Woof Wash",
    category: "Pet laundromats",
    blurb:
      "Self-service pet textiles wash with pet-safe enzyme detergent. Drying rack and lint-removal station included.",
    address: " Ang Mo Kio",
    priceFrom: "$10/load",
    website: "https://woofwash.sg",
  },
  {
    name: "The Pet Laundry Co.",
    category: "Pet laundromats",
    blurb:
      "Drop-off service for heavily soiled crate liners and waterproof beds. 24-hour turnaround.",
    address: " Kallang",
    priceFrom: "$15/kg",
    website: "https://petlaundry.sg",
    phone: "+65 6244 5520",
  },
  {
    name: "Country Boarding by Annie",
    category: "Boarding",
    blurb:
      "Annie hosts 6 dogs at a time in her landed home with a large garden. Daily walks, photo updates, no kennels.",
    address: " Lim Chu Kang",
    priceFrom: "$55/night",
    website: "https://countryboarding.sg",
    phone: "+65 9888 3401",
  },
  {
    name: "The Wagington Hotel & Resort",
    category: "Boarding",
    blurb:
      "Boutique hotel suites with private patios. Webcam access, daily grooming, and pool sessions for water-lovers.",
    address: " Cluny Court",
    priceFrom: "$95/night",
    website: "https://wagington.com",
    phone: "+65 6471 5152",
  },
  {
    name: "Sembawang Senior Pet Stay",
    category: "Boarding",
    blurb:
      "Specialised in older and medical-needs dogs. Quiet rooms, soft bedding, ex-vet-tech overnight on duty.",
    address: " Sembawang",
    priceFrom: "$70/night",
    website: "https://seniorpetstay.sg",
    phone: "+65 6555 0142",
  },
  {
    name: "The Patient Groomer",
    category: "Grooming",
    blurb:
      "One dog at a time, no cages, no dryers if your dog hates them. Specialises in anxious and elderly pups.",
    address: " Tanjong Pagar",
    priceFrom: "$80",
    website: "https://patientgroomer.sg",
    phone: "+65 9221 7700",
  },
  {
    name: "Soapy Tails Mobile Grooming",
    category: "Grooming",
    blurb:
      "Self-contained grooming van comes to your block. Hydrobath, hand-finished cuts, quiet clippers.",
    address: " Mobile, islandwide",
    priceFrom: "$95",
    website: "https://soapytails.sg",
    phone: "+65 8123 9090",
  },
  {
    name: "Bishan Tail & Trim",
    category: "Grooming",
    blurb:
      "Neighbourhood favourite by groomer Helen. Walk-in nail trims, breed-standard cuts, gentle senior packages.",
    address: " Bishan",
    priceFrom: "$55",
    website: "https://tailtrim.sg",
    phone: "+65 6258 4488",
  },
];

const DOG_RUNS = [
  {
    sortOrder: 1,
    name: "Bishan-Ang Mo Kio Park Dog Run (It consists of two parts)",
    area: " Central",
    size: "Approximately 240 Sqm",
    description: "",
    address: "453 Ang Mo Kio Ave 1, Singapore 569972",
    openingHours: "24/7",
  },
  {
    sortOrder: 2,
    name: "Toa Payoh Dog Run Park",
    area: "Central",
    size: "Approximately 420 Sqm",
    description: "",
    address: "Toa Payoh Lorong 1 near Blk 128.",
    openingHours: "7am - 9pm",
  },
  {
    sortOrder: 3,
    name: "Potong Pasir Dog Run",
    area: "Central",
    size: "approximately: 850 Sqm",
    description: "",
    address: "Potong Pasir Ave 3, S357682",
  },
  {
    sortOrder: 4,
    name: "Tiong Bahru Dog Run Park",
    area: "Central",
    size: "approximately 2,100 Sqm",
    description: "",
    address: "1 Henderson Rd, Singapore 15956",
  },
  {
    sortOrder: 5,
    name: "East Coast Dog Run Park",
    area: "East",
    size: "Approximately 400 square meters",
    description: "",
    address: "Parkland Green, East Coast Park Service Rd, Singapore 449875",
  },
  {
    sortOrder: 6,
    name: "Bedok Town Park Dog Run",
    area: "East",
    size: "Approximately 500–600 square meters",
    description: "",
    address: "* Bedok Town Park, along Bedok North Road.",
    openingHours: "Open 24 hours daily",
  },
  {
    sortOrder: 7,
    name: "Pasir Ris Park Dog Run",
    area: "East",
    size: "~ Approximately 800 sqm",
    description: "",
    address: "125 Pasir Ris Rd (Near Carpark E).",
    openingHours: "24/7",
  },
  {
    sortOrder: 8,
    name: "Telok Kurau Dog Run",
    area: "East",
    size: "~ Approximately 400–500 Sqm",
    description: "",
    address:
      "Telok Kurau Park, located at the junction of Telok Kurau Lorong N and Lorong M.",
    openingHours: "24/7",
  },
  {
    sortOrder: 9,
    name: "Tampines Boulevard Park Dog Run",
    area: "East",
    size: "Approximately 1,200 sqm",
    description: "",
    address: "Along Tampines Ave 12.",
    openingHours: "24/7",
  },
  {
    sortOrder: 10,
    name: "Katong Park Dog Run Park",
    area: "East",
    size: "Approximately 150 sqm (Small/Cozy)",
    description: "",
    address: "Junction of Meyer Road and Fort Road.",
    openingHours: "24/7 (Lights until 10 PM)",
  },
  {
    sortOrder: 11,
    name: "Lengkong Enam Interim Park Dog Run",
    area: "East",
    size: "Approximately 1,000 sqm",
    description: "",
    address: "Along Jalan Selamat and Lengkong Tujuh.",
    openingHours: "24/7",
  },
  {
    sortOrder: 12,
    name: "Mariam Way Dog Run Park",
    area: "East",
    size: "Approximately 300 sqm",
    description: "",
    address: "Mariam Way Playground.",
    openingHours: "24/7",
  },
  {
    sortOrder: 13,
    name: "Opera Estate Dog Run",
    area: "East",
    size: "Approximately 300–400 Sqm",
    description: "",
    address:
      "Located at Opera Estate Football Field, along Swan Lake Avenue (near the junction of Fidelio Street), Singapore 455707.",
    openingHours: "Open 24 hours daily",
  },
  {
    sortOrder: 14,
    name: "Koon Seng Park Dog Run",
    area: "East",
    size: "Approximately 250-300 Sqm",
    description: "",
    address:
      "Located within Koon Seng Park, at the junction of Koon Seng Road and Joo Chiat Lane, Singapore 427013.",
    openingHours: "Open 24 hours daily",
    image: "koon-seng.png",
  },
  {
    sortOrder: 15,
    name: "Guillemard Road Open Space Dog Run",
    area: "East",
    size: "Approximately 300–400 Sqm",
    description: "",
    address:
      "Located at the junction of Guillemard Road and Lorong 22 Geylang (opposite the former Guillemard Camp area).",
    openingHours: "Open 24 hours daily",
  },
  {
    sortOrder: 16,
    name: "Sembawang Dog Run Park",
    area: "North",
    size: "Approximately 2,700 sqm",
    description: "",
    address: "Northern end of Sembawang Road.",
    openingHours: "24/7 (No dedicated lighting)",
  },
  {
    sortOrder: 17,
    name: "Yishun Park Dog Run",
    area: "North",
    size: "Approximately 500 sqm",
    description: "",
    address: "Yishun Central (Opposite Adora Green). Hours: 24/7.",
  },
  {
    sortOrder: 18,
    name: "Punggol Waterway Park Dog Run",
    area: "North-East",
    size: "Approximately 500 sqm",
    description: "",
    address: "Sentul Crescent. Hours: 24/7.",
  },
  {
    sortOrder: 19,
    name: "Rivervale Dog Run (Sengkang)",
    area: "North-East",
    size: "Approximately 450 sqm",
    description: "",
    address: "Near Block 178 Rivervale Crescent. Hours: 7:00 AM – 10:00 PM.",
  },
  {
    sortOrder: 20,
    name: "Woodlands Waterfront Dog Run",
    area: "North",
    size: "Approximately 600 sqm",
    description: "",
    address: "Admiralty Road West. Hours: 24/7.",
  },
  {
    sortOrder: 21,
    name: "K9 Park @ NEX (Mall Dog Run)",
    area: "North-East",
    size: "Approximately 180 sqm",
    description: "",
    address: "23 Serangoon Central, NEX Level 4R",
    openingHours: "10:30 AM – 10:30 PM",
  },
  {
    sortOrder: 22,
    name: "Sun Plaza Park Dog Run",
    area: "East",
    size: "Approximately 600 sqm",
    description: "",
    address:
      "Tampines Avenue 7 and Tampines Avenue 9, Singapore 520558. (The dog run is situated closer to the Tampines Regional Library and the Tampines Eco Green entrance side of the park).",
    openingHours: "24/7",
  },
  {
    sortOrder: 23,
    name: "West Coast Park Dog Run",
    area: "West",
    size: "Massive (Part of the 50-hectare park)",
    description: "",
    address: "Parallel to West Coast Highway (Near Carpark 1).",
    openingHours: "24/7 (Lights until 7 PM)",
  },
  {
    sortOrder: 24,
    name: "Clementi Woods Park Dog Run",
    area: "West",
    size: "Approximately 4,000 sqm",
    description: "",
    address: "152 West Coast Road (next to West Coast Plaza).",
    openingHours: "24/7 (Lights until 7 AM)",
  },
  {
    sortOrder: 25,
    name: "Jurong Lake Gardens Dog Run",
    area: "West",
    size: "Approximately 2,200 sqm",
    description: "",
    address: "104 Yuan Ching Road.",
    openingHours: "8:00 AM – 10:00 PM",
  },
  {
    sortOrder: 26,
    name: "Bukit Gombak Park Dog Run",
    area: "West",
    size: "Approximately 400 sqm",
    description: "",
    address: "Bukit Batok West Ave 5.",
    openingHours: "24/7",
  },
  {
    sortOrder: 27,
    name: "Villa Verde Park Dog Run",
    area: "West",
    size: "Approximately 400-500 Sqm",
    description: "",
    address:
      "Located within Villa Verde Park, at the end of Verde View, Singapore 688644 (along the Pang Sua Park Connector)",
    openingHours: "Open 24 hours daily",
  },
];

export const seedDogRuns = internalMutation({
  handler: async (ctx) => {
    const existing = await ctx.db.query("dogRuns").collect();
    if (existing.length > 0) return "Dog runs already seeded.";
    for (const run of DOG_RUNS) {
      await ctx.db.insert("dogRuns", { waterPoint: false, ...run });
    }
    return `Seeded ${DOG_RUNS.length} dog runs.`;
  },
});

export const seedServices = internalMutation({
  handler: async (ctx) => {
    const existing = await ctx.db.query("services").collect();
    if (existing.length > 0) return "Services already seeded.";
    for (const svc of SERVICES) {
      await ctx.db.insert("services", { featured: false, ...svc });
    }
    return `Seeded ${SERVICES.length} services.`;
  },
});

const BLOG_POSTS = [
  {
    category: "Adoption Story",
    title: "Mochi finds a quiet flat in Tiong Bahru",
    slug: "mochi-finds-a-quiet-flat-in-tiong-bahru",
    date: "12 May 2026",
    author: "Aishah, foster carer",
    cover: "https://placedog.net/800/500?id=401",
    excerpt:
      "After three months in foster, our shy little Shih Tzu mix finally has a corner of her own. We visited her new family last weekend — and yes, she still squeaks when you scratch her chin.",
    readTime: "4 min read",
    body: `<p>For her first eight weeks in foster, Mochi lived under my dining table. Not beside it — under it, behind a curtain of chair legs, where she could see the room without the room seeing her.</p>
<p>She came to us from a hoarding case in the north of the island: one of fourteen dogs in a two-room flat, none of them socialised, all of them frightened of hands. Mochi was the smallest and the quietest, and for a long time we worried that quiet was all she had left.</p>
<h2>The squeak</h2>
<p>The turning point, as it often is, was nonsense. One evening I scratched her chin and she let out a single, indignant squeak — half hiccup, half protest. It was the first sound she'd made that wasn't fear. I froze. She did it again. Within a week she was following me to the kitchen, squeaking the whole way, as if narrating.</p>
<p>That squeak is now famous. Her adopters — a retired couple in a quiet Tiong Bahru walk-up — heard it at our open day and were, in their own words, "completely finished." They'd come to meet a different dog entirely.</p>
<h2>Home</h2>
<p>We visited last weekend. Mochi has a basket by the window, a strict 7am breakfast appointment, and a corner of the sofa that is understood by all parties to be hers. She still hides when the doorbell rings. But she comes out again — and she still squeaks when you scratch her chin.</p>`,
  },
  {
    category: "Guidelines",
    title: "What HDB approval actually means for your dog",
    slug: "what-hdb-approval-actually-means-for-your-dog",
    date: "06 May 2026",
    author: "Homeward Team",
    cover: "https://placedog.net/800/500?id=402",
    excerpt:
      "A plain-English guide to Project ADORE, the Mixed Breed Scheme, and the height and weight rules that decide which dogs can call an HDB flat home. With examples and what to do if you're unsure.",
    readTime: "7 min read",
    body: `<p>"HDB-approved" is one of the most misunderstood phrases in Singapore dog adoption. People treat it like a single stamp of approval, when in reality it's a set of overlapping rules — and knowing the difference is what decides whether a dog can legally call a flat home.</p>
<h2>Project ADORE, in plain English</h2>
<p>Project ADORE (ADoption and REhoming of dogs) is a scheme that allows certain larger local mixed-breed dogs to be kept in HDB flats, provided they meet specific conditions and the dog is sourced through an approved partner. It exists precisely because the default HDB rules were designed around small breeds and excluded most rescue dogs.</p>
<p>Under ADORE, an adopted dog must be microchipped, sterilised, licensed, and — importantly — under a height and weight cap measured at the shoulder.</p>
<h2>The Mixed Breed Scheme</h2>
<p>Separately, HDB permits a list of approved small breeds and, through the Mixed Breed Scheme, local Singapore Specials that fall within the size limits. The practical effect: a 15kg Singapore Special may qualify where a purebred of the same size does not.</p>
<h2>What to do if you're unsure</h2>
<p>Don't guess. Before committing to a dog, ask the welfare group three things: is this dog ADORE-eligible, what is its adult height and weight, and will they support the licensing paperwork. A responsible group will have answers ready — and if they don't, that tells you something too.</p>`,
  },
  {
    category: "Adoption Story",
    title: "Biscuit's first year on a sofa",
    slug: "biscuits-first-year-on-a-sofa",
    date: "28 Apr 2026",
    author: "Marcus, adopter",
    cover: "https://placedog.net/800/500?id=403",
    excerpt:
      "A Singapore Special who spent four years in a back lane is now hogging the air-con and judging the neighbours. We catch up with Biscuit and his adopter, twelve months on.",
    readTime: "6 min read",
    body: `<p>Biscuit spent the first four years of his life in a back lane in the west of Singapore, surviving on scraps and the kindness of one hawker who left water out. When we trapped him for sterilisation, he was so flat against the ground he looked like a shadow that had given up.</p>
<h2>Twelve months later</h2>
<p>Today Biscuit is hogging the air-con in a Clementi flat, sleeping on his back with all four legs in the air, and — according to his adopter Marcus — "judging the neighbours through the window like a retired magistrate."</p>
<p>"The first month was hard," Marcus admits. "He didn't know what a sofa was for. He didn't know what to do with a toy. He flinched at brooms." Singapore Specials carry their street years with them, and decompression takes time.</p>
<h2>What changed</h2>
<p>Routine, mostly. The same walk at the same time. The same words. Marcus didn't force affection — he just made the flat a place where nothing bad ever happened, over and over, until Biscuit believed it.</p>
<p>"I didn't rescue him," Marcus says. "I just provided the air-con. He did the rest."</p>`,
  },
  {
    category: "Guidelines",
    title: "Your first 30 days with a rescue dog",
    slug: "your-first-30-days-with-a-rescue-dog",
    date: "19 Apr 2026",
    author: "Dr. Lim, partner vet",
    cover: "https://placedog.net/800/500?id=404",
    excerpt:
      "The 3-3-3 rule, decompression, the vet visit timeline, and what to actually do (and not do) in the first month. Required reading for new adopters.",
    readTime: "9 min read",
    body: `<p>The first month with a rescue dog is the one that matters most — and the one most new adopters get wrong, usually out of love. Here's the framework we give every adopter before they take a dog home.</p>
<h2>The 3-3-3 rule</h2>
<p>Three days to decompress. Three weeks to learn your routine. Three months to start feeling at home. In the first three days, expect your dog to be overwhelmed, possibly shut down, possibly not eating much. This is normal. Do less, not more.</p>
<h2>Decompression</h2>
<p>Resist the urge to introduce your new dog to everyone you know. No parties, no dog cafés, no big walks on day one. Give them a small, safe space and let them choose when to explore it. A dog that hides is not a sad dog — it's a sensible one.</p>
<h2>The vet visit</h2>
<p>Book a wellness check within the first week, but don't make it day one unless there's an emergency. You want the first car ride and the first vet to come after a little trust has formed, not before.</p>
<h2>What not to do</h2>
<p>Don't bathe them immediately. Don't take the collar off outdoors. Don't punish fear. And don't panic if week one looks nothing like the dog you met at the shelter — you're meeting the real one now, and they're meeting you.</p>`,
  },
  {
    category: "Tips",
    title: "Walking your dog in Singapore's heat",
    slug: "walking-your-dog-in-singapores-heat",
    date: "11 Apr 2026",
    author: "Homeward Team",
    cover: "https://placedog.net/800/500?id=405",
    excerpt:
      "Pavement temperature, hydration, the seven-second tarmac test, and the best times to go out without melting your dog. A short, hot-weather field guide.",
    readTime: "5 min read",
    body: `<p>Singapore's pavements can hit 50°C on a sunny afternoon. Your dog walks on those pavements barefoot. The maths is not in their favour, and heatstroke in dogs can turn fatal faster than most owners expect.</p>
<h2>The seven-second test</h2>
<p>Before any walk, press the back of your hand flat against the pavement for seven seconds. If you can't hold it there comfortably, it's too hot for paws. Simple, free, and it has saved more pads than any product on the market.</p>
<h2>Timing</h2>
<p>Walk before 8am or after 7pm. The midday sun isn't just uncomfortable — it's dangerous, especially for flat-faced breeds and seniors who can't cool themselves efficiently. A shorter walk in the cool is worth more than a long one in the heat.</p>
<h2>Hydration and warning signs</h2>
<p>Carry water on every outing. Watch for heavy panting, drooling, bright red gums, and stumbling — these are early heatstroke signs. If you see them, move to shade, wet the paws and belly with cool (not ice-cold) water, and call your vet immediately.</p>`,
  },
  {
    category: "Adoption Story",
    title: "Pepper, the senior schnauzer, picks her person",
    slug: "pepper-the-senior-schnauzer-picks-her-person",
    date: "02 Apr 2026",
    author: "Aishah, foster carer",
    cover: "https://placedog.net/800/500?id=406",
    excerpt:
      "Some dogs choose their family. Pepper walked past six prospective adopters at our open day and sat on the seventh's foot. The rest, as they say, is history.",
    readTime: "5 min read",
    body: `<p>People assume adopters choose dogs. Anyone who's worked an open day knows it's often the other way around.</p>
<h2>The open day</h2>
<p>Pepper is an eleven-year-old schnauzer surrendered when her elderly owner moved into care. Senior dogs are the hardest to rehome — everyone wants a puppy, few want grey muzzles and vet bills. We braced ourselves for a long wait.</p>
<p>At our April open day, six prospective adopters knelt down to greet her. Pepper walked past every one of them — polite but unmoved — and sat squarely on the seventh person's foot. Then she leaned her whole weight against their shin and sighed.</p>
<h2>The seventh person</h2>
<p>That person hadn't even come for a dog. They'd driven a friend to the event. They left having filled in an adoption form, slightly dazed, asking us what senior dogs eat.</p>
<p>Pepper's been home three weeks now. She sleeps eighteen hours a day, supervises dinner preparation, and still picks her person — following them room to room, sitting on the same foot, every evening.</p>`,
  },
  {
    category: "Guidelines",
    title: "Fostering 101: what we're actually asking",
    slug: "fostering-101-what-were-actually-asking",
    date: "24 Mar 2026",
    author: "Homeward Team",
    cover: "https://placedog.net/800/500?id=407",
    excerpt:
      "Fostering isn't permanent adoption — but it's also not babysitting. A clear breakdown of the time, money and emotional commitment of being a foster carer, and why we need more of them.",
    readTime: "8 min read",
    body: `<p>Every welfare group in Singapore is short on the same thing: foster homes. And every group hears the same hesitations. So let's be clear about what fostering actually is — and isn't.</p>
<h2>It isn't permanent</h2>
<p>Fostering is temporary care for a dog between rescue and adoption. You're not committing to keep the dog forever — you're giving them a home environment to decompress, learn house manners, and become adoptable. Most fosters last a few weeks to a few months.</p>
<h2>It isn't babysitting</h2>
<p>But it's also real work. A foster dog may not be toilet-trained. They may have medical needs, fear of stairs, separation anxiety, or no idea how to be alone. You're not minding a pet — you're rehabilitating one. The group covers vet costs and supplies; you provide the patience.</p>
<h2>Why we need you</h2>
<p>A dog in foster is a dog out of a kennel — calmer, healthier, and far more likely to be adopted because we can finally tell adopters how they behave in a home. Every foster home opens a kennel for the next dog off the street. The maths is brutal and simple: more fosters, more lives.</p>`,
  },
  {
    category: "Tips",
    title: "Introducing your rescue to a resident pet",
    slug: "introducing-your-rescue-to-a-resident-pet",
    date: "15 Mar 2026",
    author: "Dr. Lim, partner vet",
    cover: "https://placedog.net/800/500?id=408",
    excerpt:
      "Slow, neutral, no eye contact. A step-by-step plan for the first week of dog-to-dog and dog-to-cat introductions, with the warning signs to watch for.",
    readTime: "6 min read",
    body: `<p>Bringing a rescue dog into a home that already has a pet is where many adoptions wobble. Done slowly, it works almost every time. Done in a hurry, it can sour a relationship before it begins.</p>
<h2>The three rules</h2>
<p>Slow. Neutral. No eye contact. Write them on your hand if you have to. The instinct to "just let them meet and sort it out" is the single most common mistake we see.</p>
<h2>Day by day</h2>
<p>Start with scent only — swap blankets between the resident pet and the newcomer before they ever meet. Then parallel walks on neutral ground, several metres apart, no forced interaction. Let them exist near each other before they interact with each other.</p>
<p>For dog-to-cat introductions, the cat must always have an escape route and high ground. Never trap either animal in a corner to "get it over with."</p>
<h2>Warning signs</h2>
<p>Stiff bodies, hard stares, raised hackles, and frozen stillness are all signals to calmly increase distance. Growling is communication, not failure — it's the warning before the bite, and a dog that's allowed to growl is a dog telling you what it needs.</p>`,
  },
];

export const seedBlogPosts = internalMutation({
  handler: async (ctx) => {
    const existing = await ctx.db.query("blogPosts").collect();
    if (existing.length > 0) return "Blog posts already seeded.";
    for (const post of BLOG_POSTS) {
      await ctx.db.insert("blogPosts", post);
    }
    return `Seeded ${BLOG_POSTS.length} blog posts.`;
  },
});
