import { internalMutation } from "./_generated/server";
import { v } from "convex/values";

const VETS = [
  {
    name: "Aavc-Animal & Avian Veterinary Clinic",
    block: "716",
    street: "YISHUN STREET 71",
    floor: "1",
    unit: "254",
    postalCode: "760716",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Acacia Vet & Surgery",
    block: "338",
    street: "ANG MO KIO AVENUE 1",
    floor: "1",
    unit: "1671",
    building: "TECK GHEE COURT",
    postalCode: "560338",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Ace Vet Care",
    block: "271",
    street: "BALESTIER ROAD",
    building: "VICTORY POINT",
    postalCode: "329722",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Advanced Vetcare",
    block: "26",
    street: "JALAN PARI BURONG",
    building: "PICARDY GARDEN",
    postalCode: "488692",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Advanced Vetcare",
    block: "18",
    street: "JALAN PARI BURONG",
    building: "PICARDY GARDEN",
    postalCode: "488684",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Advanced Vetcare",
    block: "283",
    street: "OUTRAM ROAD",
    postalCode: "169068",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Advanced Vetcare @ Balestier",
    block: "564A",
    street: "BALESTIER ROAD",
    postalCode: "329880",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Allpets & Aqualife Vets Pte Ltd",
    block: "24",
    street: "JALAN KELULUT",
    floor: "1",
    unit: "1",
    postalCode: "809041",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Amber Cat Vet Pte Ltd",
    block: "48",
    street: "BURNFOOT TERRACE",
    building: "FRANKEL ESTATE",
    postalCode: "459836",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Amber Veterinary Practice Pte Ltd",
    block: "50",
    street: "BURNFOOT TERRACE",
    postalCode: "459837",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Animal Medical Centre (Vet@Rv)",
    block: "78",
    street: "INDUS ROAD",
    floor: "1",
    unit: "487",
    postalCode: "161078",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Animal Wellness Centre Pte Ltd",
    block: "1",
    street: "VISTA EXCHANGE GREEN",
    floor: "1",
    unit: "15",
    building: "THE STAR",
    postalCode: "138617",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Animal Wellness Referral Centre Pte Ltd",
    block: "200",
    street: "BUKIT TIMAH ROAD",
    floor: "1",
    unit: "1",
    building: "ATLAND HOUSE",
    postalCode: "229862",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Animal World Veterinary Clinic",
    block: "16",
    street: "YIO CHU KANG ROAD",
    floor: "1",
    postalCode: "545527",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Apex Veterinary Clinic",
    block: "462",
    street: "RIVER VALLEY ROAD",
    unit: "462",
    postalCode: "248347",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Apex Veterinary Medical Centre Pte Ltd Punggol",
    block: "418",
    street: "NORTHSHORE DRIVE",
    floor: "2",
    unit: "213",
    postalCode: "820418",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Atlas Veterinary Clinic & Surgery",
    block: "163",
    street: "BUKIT MERAH CENTRAL",
    floor: "3",
    unit: "3579",
    postalCode: "150163",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Atlas Veterinary Clinic & Surgery",
    block: "163",
    street: "BUKIT MERAH CENTRAL",
    floor: "3",
    unit: "3573",
    postalCode: "150163",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Avh Animal Ark Veterinary Group",
    block: "139",
    street: "TAMPINES STREET 11",
    floor: "1",
    unit: "54",
    postalCode: "521139",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Avh Animal Ark Veterinary Group (Springleaf)",
    block: "5",
    street: "MANDAI ROAD",
    postalCode: "779391",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Barkway Pet Health Pte. Ltd.",
    block: "169",
    street: "MACPHERSON ROAD",
    floor: "1",
    postalCode: "348535",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Beecroft Animal Specialist And Emergency Hospital",
    block: "991E",
    street: "ALEXANDRA ROAD",
    floor: "1",
    unit: "27",
    postalCode: "119973",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Bluewater Vet Acupuncture & Rehabilitation",
    block: "16",
    street: "SIN MING ROAD",
    floor: "1",
    unit: "9",
    building: "SIN MING PLAZA",
    postalCode: "575585",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Brighton Vet Care (Bukit Timah)",
    block: "611",
    street: "BUKIT TIMAH ROAD",
    postalCode: "269712",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Brighton Vet Care (Katong)",
    block: "438",
    street: "JOO CHIAT ROAD",
    postalCode: "427651",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Brighton Vet Care (Serangoon Garden)",
    block: "74",
    street: "SERANGOON GARDEN WAY",
    building: "SERANGOON GARDEN ESTATE",
    postalCode: "555970",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Canopy Veterinary Centre",
    block: "1",
    street: "YUAN CHING ROAD",
    floor: "3",
    unit: "3",
    building: "SUPERBOWL JURONG",
    postalCode: "618640",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Care Veterinary Clinic Pte Ltd",
    block: "124",
    street: "LORONG 1 TOA PAYOH",
    floor: "1",
    unit: "473",
    postalCode: "310124",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Clinic For Pets",
    block: "1015",
    street: "GEYLANG EAST AVENUE 3",
    floor: "1",
    unit: "141",
    building: "GEYLANG EAST INDUSTRIAL ESTATE",
    postalCode: "389730",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Clover Vet",
    block: "678",
    street: "HOUGANG AVENUE 8",
    floor: "1",
    unit: "503",
    postalCode: "530678",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Companion Animal Surgery Pte Ltd",
    block: "12",
    street: "BOON TECK ROAD",
    floor: "1",
    unit: "5",
    postalCode: "329586",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Dr Paws Vet Care",
    block: "77",
    street: "LUCKY HEIGHTS",
    building: "LUCKY COURT",
    postalCode: "467626",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Edmond Tan Veterinary Surgery",
    block: "151",
    street: "Serangoon North Avenue 2",
    floor: "1",
    unit: "65",
    postalCode: "550151",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Evervet Veterinary Clinic",
    block: "212",
    street: "CHANGI ROAD",
    floor: "1",
    unit: "212",
    postalCode: "419735",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Evervet Veterinary Clinic Pte Ltd",
    block: "123",
    street: "BEDOK NORTH STREET 2",
    floor: "1",
    unit: "154",
    postalCode: "460123",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Frankel Veterinary Centre",
    block: "101",
    street: "FRANKEL AVENUE",
    floor: "1",
    postalCode: "458224",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Fur Folks Home",
    block: "1212",
    street: "UPPER THOMSON ROAD",
    floor: "1",
    postalCode: "787127",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Furiends Veterinary Clinic",
    block: "58",
    street: "YIO CHU KANG ROAD",
    postalCode: "545564",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Furrytails Veterinary Clinic Pte Ltd",
    block: "2",
    street: "JALAN LOKAM",
    building: "KENSINGTON SQUARE",
    postalCode: "537846",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Gaia Veterinary Centre (Jalan Besar)",
    block: "415",
    street: "JALAN BESAR",
    postalCode: "209016",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Gaia Veterinary Centre (Parksuites)",
    block: "24",
    street: "HOLLAND GROVE ROAD",
    floor: "1",
    unit: "12",
    building: "PARKSUITES",
    postalCode: "278803",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Genesis Veterinary Clinic",
    block: "935",
    street: "YISHUN CENTRAL 1",
    floor: "1",
    unit: "43",
    postalCode: "760935",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Gentle Oak Veterinary Clinic",
    block: "21",
    street: "GHIM MOH ROAD",
    floor: "1",
    unit: "225",
    postalCode: "270021",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Hillside Veterinary Surgery",
    block: "787A",
    street: "UPPER SERANGOON ROAD",
    postalCode: "534655",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Hope Veterinary Care",
    block: "1017",
    street: "UPPER SERANGOON ROAD",
    floor: "1",
    unit: "1",
    postalCode: "534755",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Island Veterinary Clinic Pte Ltd",
    block: "114",
    street: "JURONG EAST STREET 13",
    floor: "1",
    unit: "404",
    postalCode: "600114",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "James Tan Veterinary Centre Pte Ltd",
    block: "230",
    street: "WHITLEY ROAD",
    building: "JAMES TAN HOSPITAL",
    postalCode: "297823",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Jireh Veterinary Clinic Pte Ltd",
    block: "530",
    street: "BALESTIER ROAD",
    floor: "1",
    unit: "4",
    postalCode: "329857",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Kai Vets Pte Ltd",
    block: "144",
    street: "TAMPINES STREET 12",
    floor: "1",
    unit: "392",
    postalCode: "521144",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Kin Veterinary Clinic",
    block: "780",
    street: "UPPER BUKIT TIMAH ROAD",
    postalCode: "678125",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Landon Veterinary Specialist Hospital",
    block: "41",
    street: "ENG KONG TERRACE",
    building: "ENG KONG PARK",
    postalCode: "599013",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Light Of Life Veterinary Clinic And Services Llp",
    block: "703",
    street: "Bedok Reservoir Road",
    floor: "1",
    unit: "3508",
    postalCode: "470703",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Maranatha Veterinary Clinic",
    block: "77",
    street: "TELOK BLANGAH DRIVE",
    floor: "1",
    unit: "234",
    postalCode: "100077",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Monster Pet Vet",
    block: "6",
    street: "EVERTON PARK",
    floor: "1",
    unit: "16",
    postalCode: "80006",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Mount Pleasant Animal Medical Centre (Bedok)",
    block: "158",
    street: "BEDOK SOUTH AVENUE 3",
    floor: "1",
    unit: "577",
    postalCode: "460158",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Mount Pleasant Animal Medical Centre (Clementi)",
    block: "105",
    street: "CLEMENTI STREET 12",
    floor: "1",
    unit: "18",
    building: "SUNSET WAY RESIDENCE",
    postalCode: "120105",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Mount Pleasant Animal Medical Centre (Farrer)",
    block: "3",
    street: "QUEEN'S ROAD",
    floor: "2",
    unit: "141",
    building: "FARRER GARDENS",
    postalCode: "260003",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Mount Pleasant Veterinary Centre (2008)",
    block: "2",
    street: "JALAN GELENGGANG",
    building: "SEMBAWANG HILLS ESTATE",
    postalCode: "578187",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Mount Pleasant Veterinary Centre (East)",
    block: "152",
    street: "EAST COAST ROAD",
    postalCode: "428855",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Mount Pleasant Veterinary Centre (Yishun)",
    block: "236",
    street: "YISHUN RING ROAD",
    floor: "1",
    unit: "1010",
    building: "YISHUN HEARTS",
    postalCode: "760236",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "My Animal Dispensary Pte Ltd",
    block: "1",
    street: "WEST COAST DRIVE",
    floor: "1",
    unit: "15",
    building: "NEWEST",
    postalCode: "128020",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "My Family Vet Clinic And Surgery Pte Ltd",
    block: "265",
    street: "BUKIT BATOK EAST AVENUE 4",
    floor: "1",
    unit: "403",
    postalCode: "650265",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Nam Sang Veterinary Clinic Pte Ltd",
    block: "2",
    street: "BALESTIER ROAD",
    floor: "1",
    unit: "699",
    postalCode: "320002",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Namly Veterinary Surgery Pte Ltd",
    block: "74",
    street: "NAMLY PLACE",
    building: "SHAMROCK PARK",
    postalCode: "267223",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Oasis Vet",
    block: "15",
    street: "VENUS ROAD",
    building: "WINDSOR PARK",
    postalCode: "574302",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Ohana Vetcare",
    block: "258",
    street: "PASIR RIS STREET 21",
    floor: "4",
    unit: "1",
    postalCode: "510258",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Omnivet",
    block: "31",
    street: "JALAN MAS PUTEH",
    building: "PASIR PANJANG GARDENS",
    postalCode: "128633",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "P.A.W (People Animal Wellness) Veterinary Centre Pte Ltd",
    block: "112",
    street: "BUKIT PURMEI ROAD",
    floor: "1",
    unit: "207",
    postalCode: "90112",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Passion Veterinary Clinic",
    block: "136",
    street: "MARSILING ROAD",
    floor: "1",
    unit: "2180",
    postalCode: "730136",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Passion Veterinary Clinic Pte Ltd",
    block: "111",
    street: "WOODLANDS STREET 13",
    floor: "1",
    unit: "86",
    postalCode: "730111",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Paws & Claws Veterinary Surgery",
    block: "285",
    street: "YISHUN AVENUE 6",
    floor: "1",
    unit: "6",
    building: "FICUS VALE",
    postalCode: "760285",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Paws & Claws Veterinary Surgery",
    block: "6",
    street: "SIN MING ROAD",
    floor: "1",
    unit: "4",
    building: "SIN MING PLAZA",
    postalCode: "575585",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Pet Care Centre And Clinic Pte Ltd",
    block: "14",
    street: "WARINGIN PARK",
    building: "PET CARE CENTRE & CLINIC",
    postalCode: "416318",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Pet Clinic Pte Ltd",
    block: "211",
    street: "SERANGOON AVENUE 4",
    floor: "1",
    unit: "12",
    postalCode: "550211",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Pet Space (Singapore) Pte Ltd",
    block: "482",
    street: "SERANGOON ROAD",
    floor: "1",
    unit: "1",
    postalCode: "218149",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Pets Avenue Veterinary Clinic (Beauty World)",
    block: "50",
    street: "JALAN JURONG KECHIL",
    building: "JK BUILDING",
    postalCode: "598578",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Pets Avenue Veterinary Clinic (Farrer)",
    block: "8",
    street: "EMPRESS ROAD",
    floor: "1",
    unit: "11",
    building: "FARRER GARDENS",
    postalCode: "260008",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Pets Avenue Veterinary Clinic (River Valley)",
    block: "241",
    street: "RIVER VALLEY ROAD",
    floor: "2",
    unit: "1",
    building: "GIANURN BUILDING",
    postalCode: "238298",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Pets Avenue Veterinary Clinic (Upper Thomson)",
    block: "193",
    street: "UPPER THOMSON ROAD",
    building: "YEW LIAN PARK",
    postalCode: "574338",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Pets Avenue Veterinary Clinic And Referrals",
    block: "328",
    street: "CHANGI ROAD",
    floor: "1",
    unit: "1",
    building: "TEDGE",
    postalCode: "419803",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Point Veterinary Surgery",
    block: "541",
    street: "JURONG WEST AVENUE 1",
    floor: "1",
    unit: "1044",
    postalCode: "640541",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Rehabvet Clinic",
    block: "513",
    street: "SERANGOON ROAD",
    floor: "1",
    unit: "1",
    postalCode: "218154",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Singapore Turf Club Equine Hospital",
    block: "1",
    street: "TURF CLUB AVENUE",
    postalCode: "738078",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Singapore Veterinary (Singvet) Animal Clinic Beauty World",
    block: "66",
    street: "JALAN JURONG KECHIL",
    building: "JK BUILDING",
    postalCode: "598586",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Singapore Veterinary (Singvet) Animal Clinic Pte Ltd",
    block: "768",
    street: "WOODLANDS AVENUE 6",
    floor: "1",
    unit: "11",
    building: "WOODLANDS MART",
    postalCode: "730768",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Sora Vet",
    block: "37",
    street: "CHAI CHEE AVENUE",
    floor: "1",
    unit: "291",
    building: "ANSAR GARDEN",
    postalCode: "461037",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Spca Community Animal Clinic",
    block: "50",
    street: "SUNGEI TENGAH ROAD",
    floor: "1",
    unit: "1",
    postalCode: "699012",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Spring Veterinary Care",
    block: "123",
    street: "HOUGANG AVENUE 1",
    floor: "1",
    unit: "1412",
    postalCode: "530123",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Spring Veterinary Care Punggol",
    block: "681",
    street: "PUNGGOL DRIVE",
    floor: "1",
    unit: "16A",
    postalCode: "820681",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Stars Veterinary Clinic (Hougang Village)",
    block: "681",
    street: "HOUGANG AVENUE 8",
    floor: "1",
    unit: "841",
    postalCode: "530681",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Stars Veterinary Clinic Pte Ltd",
    block: "211",
    street: "HOUGANG STREET 21",
    floor: "1",
    unit: "301",
    postalCode: "530211",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "The Animal Clinic",
    block: "109",
    street: "CLEMENTI STREET 11",
    floor: "1",
    unit: "19",
    postalCode: "120109",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "The Animal Clinic (Katong Branch)",
    block: "55",
    street: "LORONG L TELOK KURAU",
    floor: "1",
    unit: "63",
    building: "BRIGHT CENTRE",
    postalCode: "425500",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "The Animal Doctors",
    block: "108",
    street: "ANG MO KIO AVENUE 4",
    floor: "1",
    unit: "96",
    building: "KEBUN BARU HEIGHTS",
    postalCode: "560108",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "The Animal Doctors (Tiong Bahru)",
    block: "11A",
    street: "BOON TIONG ROAD",
    floor: "2",
    unit: "7",
    building: "TIONG BAHRU VIEW",
    postalCode: "161011",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "The Cat Vet",
    block: "2",
    street: "PANDAN VALLEY",
    floor: "B1",
    unit: "204D",
    building: "ACACIA COURT",
    postalCode: "597626",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "The Eye Specialist For Animals",
    block: "299",
    street: "TANJONG KATONG ROAD",
    postalCode: "437082",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "The Gentle Vet",
    block: "291",
    street: "TANJONG KATONG ROAD",
    postalCode: "437074",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "The Joyous Vet Pte Ltd",
    block: "475",
    street: "CHOA CHU KANG AVENUE 3",
    floor: "1",
    unit: "30A",
    postalCode: "680475",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "The Pet Physician",
    block: "2",
    street: "JALAN PARI BURONG",
    building: "PICARDY GARDENS",
    postalCode: "488668",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "The Vet Ward",
    block: "112",
    street: "LAVENDER STREET",
    floor: "1",
    unit: "1",
    building: "CHANG HUA BUILDING",
    postalCode: "338728",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "The Veterinary Clinic",
    block: "31",
    street: "LORONG LIPUT",
    building: "HOLLAND VILLAGE",
    postalCode: "277742",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "The Veterinary Clinic @ Tampines Pte Ltd",
    block: "476",
    street: "TAMPINES STREET 44",
    floor: "1",
    unit: "201",
    postalCode: "520476",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "The Visiting Vets Clinic",
    block: "9",
    street: "TAMAN SERASI",
    floor: "1",
    unit: "9",
    postalCode: "257720",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Toa Payoh Vets Pte Ltd",
    block: "1002",
    street: "TOA PAYOH INDUSTRIAL PARK",
    floor: "1",
    unit: "1477",
    postalCode: "319074",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Town Vets Animal Clinic Pte Ltd",
    block: "22",
    street: "HAVELOCK ROAD",
    floor: "1",
    unit: "687",
    postalCode: "160022",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Tp Animal Clinic & Wellness Centre",
    block: "21",
    street: "TAMPINES AVENUE 1",
    building: "TEMASEK POLYTECHNIC",
    postalCode: "529757",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "United Veterinary Clinic Pte Ltd",
    block: "107",
    street: "ANG MO KIO AVENUE 4",
    floor: "1",
    unit: "148",
    building: "KEBUN BARU HEIGHTS",
    postalCode: "560107",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Ves Hospital",
    block: "232",
    street: "WHITLEY ROAD",
    building: "MOUNT PLEASANT ANIMAL HOSPITAL",
    postalCode: "297824",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Vet Affinity Pte Ltd",
    block: "151",
    street: "BUKIT BATOK STREET 11",
    floor: "1",
    unit: "248",
    postalCode: "650151",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Vet Central",
    block: "69",
    street: "LORONG 4 TOA PAYOH",
    building: "TOA PAYOH VISTA",
    postalCode: "310069",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Vet Central (Swan Lake) Pte Ltd",
    block: "19",
    street: "SWAN LAKE AVENUE",
    building: "OPERA ESTATE",
    postalCode: "455708",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Vet Practice Pte Ltd",
    block: "31",
    street: "HOLLAND CLOSE",
    floor: "1",
    unit: "219",
    postalCode: "270031",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Vet Practice Pte Ltd",
    block: "21",
    street: "LORONG KILAT",
    floor: "1",
    unit: "4",
    building: "SUN COURT",
    postalCode: "598123",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Vetmedic Animal Clinic And Surgery",
    block: "52",
    street: "JALAN MALU-MALU",
    building: "SEMBAWANG SPRINGS ESTATE",
    postalCode: "769667",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Vets For Life Animal Clinic",
    block: "27A",
    street: "LORONG LIPUT",
    building: "HOLLAND VILLAGE",
    postalCode: "277738",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Vets For Life Animal Clinic",
    block: "330",
    street: "TANJONG KATONG ROAD",
    postalCode: "437106",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Vets For Life Animal Clinic Pte Ltd",
    block: "491",
    street: "RIVER VALLEY ROAD",
    floor: "1",
    unit: "5",
    postalCode: "248371",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Vets For Pets (Lengkok Bahru)",
    block: "57",
    street: "LENGKOK BAHRU",
    floor: "1",
    unit: "475",
    postalCode: "151057",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Vets For Pets Pte Ltd",
    block: "519",
    street: "JURONG WEST STREET 52",
    floor: "1",
    unit: "157",
    postalCode: "640519",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "West Coast Vetcare Pte Ltd",
    block: "612",
    street: "CLEMENTI WEST STREET 1",
    floor: "1",
    unit: "300",
    postalCode: "120612",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Westwide Veterinary Emergency And Referral Hospital",
    block: "86",
    street: "SERANGOON GARDEN WAY",
    building: "SERANGOON GARDEN ESTATE",
    postalCode: "555982",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
  {
    name: "Woodgrove Veterinary Services Pte Ltd",
    block: "10",
    street: "WOODLANDS SQUARE",
    floor: "1",
    unit: "41",
    building: "WOODS SQUARE",
    postalCode: "737714",
    openingHours: "",
    phone: "",
    area: "",
    emergency: false,
    publicHolidays: false,
  },
];

const NAMES = [
  "Buddy",
  "Bella",
  "Charlie",
  "Luna",
  "Max",
  "Daisy",
  "Milo",
  "Ruby",
  "Cooper",
  "Lola",
];
const GENDERS = ["Male", "Female"] as const;

export const seedDogs = internalMutation({
  args: { count: v.number() },
  handler: async (ctx, args) => {
    // 1. Get existing welfare groups to link them
    const groups = await ctx.db.query("welfareGroups").collect();
    if (groups.length === 0) {
      throw new Error(
        "Please add at least one Welfare Group before seeding dogs.",
      );
    }

    for (let i = 0; i < args.count; i++) {
      const randomGroup = groups[Math.floor(Math.random() * groups.length)];
      const randomGender = GENDERS[Math.floor(Math.random() * GENDERS.length)];

      // Generate a random birthday between 1 and 10 years ago
      const yearsAgo = Math.floor(Math.random() * 10) + 1;
      const birthday = new Date();
      birthday.setFullYear(birthday.getFullYear() - yearsAgo);

      await ctx.db.insert("dogs", {
        name: `${NAMES[Math.floor(Math.random() * NAMES.length)]} ${i + 1}`,
        gender: randomGender,
        birthday: birthday.toISOString(),
        hdbApproved: Math.random() > 0.5 ? "Yes" : "No",
        welfareGroupId: randomGroup._id,
        status: "Active",
        // Using a placeholder image from your logic
        imageStorageId: undefined,
        description:
          "This is a generated dog description for testing purposes.",
      });
    }

    return `Successfully seeded ${args.count} dogs!`;
  },
});

const WELFARE_GROUPS = [
  {
    name: "SOSD — Save Our Street Dogs",
    blurb: "Singapore Specials. Sanctuary in Jalan Bahar.",
    dogsAvailable: 86,
    website: "https://sosd.org.sg",
    facebook: "https://facebook.com/sosd.sg",
    instagram: "https://instagram.com/sosd_sg",
    tiktok: "https://tiktok.com/@sosd.sg",
    youtube: "https://youtube.com/@sosdsingapore",
  },
  {
    name: "Action for Singapore Dogs",
    blurb: "Rescue, rehab, rehome. Since 2000.",
    dogsAvailable: 52,
    website: "https://asdsingapore.com",
    facebook: "https://facebook.com/ActionForSingaporeDogs",
    instagram: "https://instagram.com/asd_singapore",
  },
  {
    name: "Causes for Animals (Singapore)",
    blurb: "Community cats & rescue dogs.",
    dogsAvailable: 34,
    website: "https://causesforanimals.com",
    facebook: "https://facebook.com/CausesForAnimalsSG",
    instagram: "https://instagram.com/causesforanimals",
    youtube: "https://youtube.com/@causesforanimals",
  },
  {
    name: "Voices for Animals",
    blurb: "Senior dogs & long-stayers.",
    dogsAvailable: 41,
    website: "https://voicesforanimals.com.sg",
    facebook: "https://facebook.com/voicesforanimalssg",
    instagram: "https://instagram.com/voicesforanimalssg",
    tiktok: "https://tiktok.com/@voicesforanimals",
  },
  {
    name: "OSCAS — Oasis Second Chance",
    blurb: "Farmway shelter in Sungei Tengah.",
    dogsAvailable: 63,
    website: "https://oscas.com.sg",
    facebook: "https://facebook.com/oscas.sg",
    instagram: "https://instagram.com/oscas_sg",
  },
  {
    name: "Exclusively Mongrels Ltd",
    blurb: "Local mongrels only. Foster-first.",
    dogsAvailable: 28,
    website: "https://exclusivelymongrels.org",
    facebook: "https://facebook.com/exclusivelymongrels",
    instagram: "https://instagram.com/exclusivelymongrels",
  },
  {
    name: "Mercylight Animal Sanctuary",
    blurb: "Senior & special-needs animals.",
    dogsAvailable: 47,
    website: "https://mercylight.sg",
    facebook: "https://facebook.com/MercylightSanctuary",
    instagram: "https://instagram.com/mercylightsanctuary",
    youtube: "https://youtube.com/@mercylight",
  },
  {
    name: "Purely Adoptions",
    blurb: "Adopt-don't-shop advocacy.",
    dogsAvailable: 19,
    website: "https://purelyadoptions.com",
    facebook: "https://facebook.com/purelyadoptions",
    instagram: "https://instagram.com/purelyadoptions",
    tiktok: "https://tiktok.com/@purelyadoptions",
  },
  {
    name: "Animal Lovers League",
    blurb: "Cage-free farmway shelter.",
    dogsAvailable: 71,
    website: "https://animalloversleague.com",
    facebook: "https://facebook.com/AnimalLoversLeague",
    instagram: "https://instagram.com/animalloversleague",
  },
  {
    name: "SPCA Singapore",
    blurb: "Adoption, inspection, advocacy.",
    dogsAvailable: 38,
    website: "https://spca.org.sg",
    facebook: "https://facebook.com/spca.singapore",
    instagram: "https://instagram.com/spcasingapore",
    tiktok: "https://tiktok.com/@spcasingapore",
    youtube: "https://youtube.com/@SPCASingapore",
  },
];

export const seedWelfareGroups = internalMutation({
  handler: async (ctx) => {
    const existing = await ctx.db.query("welfareGroups").collect();
    if (existing.length > 0) return "Welfare groups already seeded.";
    for (const g of WELFARE_GROUPS) {
      const slug = g.name
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-|-$/g, "");
      await ctx.db.insert("welfareGroups", { ...g, slug, status: "Active" });
    }
    return `Seeded ${WELFARE_GROUPS.length} welfare groups.`;
  },
});

const EVENTS = [
  {
    name: "Spring Adoption Drive",
    kind: "Adoption",
    image: "https://placedog.net/1200/600?id=200",
    location: "Bishan Park Pavilion, Hall A",
    dateTime: "5 Apr 2026 to 6 Apr 2026, 8am to 9pm daily",
    short:
      "Meet 30+ rescue dogs over one weekend. On-site adoption counsellors, free goodie bags, and a quiet room for shy doggos to mingle slowly with prospective families.",
    cta: "Reserve a slot",
    tag: "Featured",
  },
  {
    name: "Homeward Annual Pet Fair",
    kind: "Pet Fair",
    image: "https://placedog.net/1200/600?id=210",
    location: "Suntec Convention Hall 401",
    dateTime: "17 May 2026, 10am to 7pm",
    short:
      "Our biggest day of the year. 40+ small businesses, vet talks, training demos, paw-print art for the kids, and a live shelter dog showcase every hour on the hour.",
    cta: "Get tickets",
  },
  {
    name: "Microchip & Vaccination Day",
    kind: "Clinic",
    image: "https://placedog.net/1200/600?id=220",
    location: "Mt Pleasant Vet, Whitley Road",
    dateTime: "22 Jun 2026, 9am to 1pm",
    short:
      "Subsidised microchipping ($15) and core vaccinations ($40) for adopted dogs and Singapore Specials. By appointment — limited to 60 slots.",
    cta: "Book a slot",
  },
  {
    name: "Sunset Sembawang Walk",
    kind: "Community",
    image: "https://placedog.net/1200/600?id=230",
    location: "Sembawang Park Boardwalk",
    dateTime: "12 Jul 2026, 5pm to 7pm",
    short:
      "A monthly community walk for adopters, fosters and curious dog-lovers. Bring water, bring your dog, bring a friend who's been thinking about adopting.",
    cta: "RSVP",
  },
  {
    name: "Senior Dogs Meet & Greet",
    kind: "Adoption",
    image: "https://placedog.net/1200/600?id=240",
    location: "Homeward Shelter, Sembawang",
    dateTime: "3 Aug 2026 to 4 Aug 2026, 11am to 5pm daily",
    short:
      "Eight of our older residents need quiet homes for their best years yet. Drop by for a slow afternoon, a cup of tea, and the company of a very good old dog.",
    cta: "Plan your visit",
  },
  {
    name: "Foster Carer Workshop",
    kind: "Training",
    image: "https://placedog.net/1200/600?id=250",
    location: "Homeward Shelter, Sembawang",
    dateTime: "14 Sep 2026, 2pm to 5pm",
    short:
      "Considering becoming a foster carer? Spend an afternoon with our team learning the basics — feeding, decompression, vet visits, and how to say goodbye.",
    cta: "Sign up free",
  },
];

export const seedEvents = internalMutation({
  handler: async (ctx) => {
    const existing = await ctx.db.query("events").collect();
    if (existing.length > 0) return "Events already seeded.";
    for (const ev of EVENTS) {
      await ctx.db.insert("events", ev);
    }
    return `Seeded ${EVENTS.length} events.`;
  },
});

export const seedVets = internalMutation({
  handler: async (ctx) => {
    const existing = await ctx.db.query("vets").collect();
    if (existing.length > 0) return "Vets already seeded.";
    for (const vet of VETS) {
      await ctx.db.insert("vets", vet);
    }
    return `Seeded ${VETS.length} vets.`;
  },
});

const SERVICES = [
  {
    name: "Paws & Pencils Studio",
    category: "Artists",
    blurb:
      "Hand-drawn graphite portraits and full-colour pastel commissions of your dog. Two-week turnaround, ships in a tube.",
    address: " Tiong Bahru",
    priceFrom: "$120",
    website: "https://pawsandpencils.sg",
    phone: "+65 9123 4567",
  },
  {
    name: "Tiny Snout Watercolours",
    category: "Artists",
    blurb:
      "Loose, joyful watercolour portraits by Bukit Timah-based illustrator Lin Wei. Originals come in A5 to A3.",
    address: " Bukit Timah",
    priceFrom: "$85",
    website: "https://tinysnout.studio",
  },
  {
    name: "Forever Paws — Clay Casting",
    category: "Artists",
    blurb:
      "Memorial paw-print clay impressions and 3D-printed scans. Often booked for end-of-life keepsakes.",
    address: " Geylang",
    priceFrom: "$60",
    website: "https://foreverpaws.sg",
    phone: "+65 8234 9921",
  },
  {
    name: "Mobile Aftercare Services",
    category: "Cremation",
    blurb:
      "Compassionate individual cremation with home pick-up. Family viewings available; ashes returned in a hand-finished urn.",
    address: " Mandai (collection)",
    priceFrom: "$280",
    website: "https://mobileaftercare.sg",
    phone: "+65 6452 0500",
  },
  {
    name: "Pets Cremation Services SG",
    category: "Cremation",
    blurb:
      "Group and private cremation, scatter garden, paw-print impression service. Open daily including public holidays.",
    address: " Ulu Pandan",
    priceFrom: "$220",
    website: "https://petscremation.sg",
    phone: "+65 8101 8101",
  },
  {
    name: "The Pet Memorial Park",
    category: "Cremation",
    blurb:
      "Memorial niches, annual remembrance day, and grief-support volunteers for families saying goodbye.",
    address: " Mandai",
    priceFrom: "$450",
    website: "https://petmemorial.sg",
  },
  {
    name: "Pawfect Provisions",
    category: "Pet shops",
    blurb:
      "Independent shop carrying air-dried kibble, raw meals, and SG-made enrichment toys. Free delivery above $80.",
    address: " Joo Chiat",
    website: "https://pawfectprovisions.sg",
    phone: "+65 6440 1188",
  },
  {
    name: "The Tail Wag Shoppe",
    category: "Pet shops",
    blurb:
      "Small but mighty — local brands, single-protein treats and harnesses fitted in-store by ex-vet-nurse Mei.",
    address: " Tiong Bahru",
    website: "https://tailwagshoppe.sg",
    phone: "+65 6555 2099",
  },
  {
    name: "Kibble & Co.",
    category: "Pet shops",
    blurb:
      "Subscription kibble (rotational proteins, freshly milled), cold-pressed treats, and the friendliest counter staff in town.",
    address: " Holland Village",
    priceFrom: "$32/mo",
    website: "https://kibbleco.sg",
  },
  {
    name: "PawFresh Meals",
    category: "Small businesses",
    blurb:
      "Gently cooked fresh meals delivered weekly across the island. Vet-formulated; bowls portioned by your dog's weight.",
    address: " Islandwide delivery",
    priceFrom: "$18/wk",
    website: "https://pawfresh.sg",
    phone: "+65 8800 4733",
  },
  {
    name: "Bone Appétit Bakery",
    category: "Small businesses",
    blurb:
      "Birthday cakes, peanut-butter pupcakes, and biscuit tins decorated with your dog's name in soft icing.",
    address: " East Coast",
    priceFrom: "$28",
    website: "https://boneappetit.sg",
  },
  {
    name: "Wagtail Apothecary",
    category: "Small businesses",
    blurb:
      "SG-made shampoos, paw balms, and calming sprays in refillable amber bottles. Small-batch, fragrance-light.",
    address: " Jurong East",
    priceFrom: "$14",
    website: "https://wagtailapothecary.sg",
  },
  {
    name: "Quiet Conversations — Lina Toh",
    category: "Animal communication",
    blurb:
      "Intuitive sessions for behaviour issues, transitions, and end-of-life care. Sessions over video or in-person.",
    address: " Online & home visits",
    priceFrom: "$160/session",
    website: "https://quietconversations.sg",
  },
  {
    name: "Heart-to-Heart Animal Talk",
    category: "Animal communication",
    blurb:
      "By Joanna Chan, certified by the Animal Spirit Network. Specialises in newly-adopted shelter dogs settling in.",
    address: " Online",
    priceFrom: "$120/session",
    website: "https://heart2heart.sg",
  },
  {
    name: "Fresh Paws Laundromat",
    category: "Pet laundromats",
    blurb:
      "Dedicated machines for pet bedding, harnesses, and cooling mats. Hot-rinse cycle for tick & flea removal.",
    address: " Bedok",
    priceFrom: "$8/load",
    website: "https://freshpaws.sg",
  },
  {
    name: "Woof Wash",
    category: "Pet laundromats",
    blurb:
      "Self-service pet textiles wash with pet-safe enzyme detergent. Drying rack and lint-removal station included.",
    address: " Ang Mo Kio",
    priceFrom: "$10/load",
    website: "https://woofwash.sg",
  },
  {
    name: "The Pet Laundry Co.",
    category: "Pet laundromats",
    blurb:
      "Drop-off service for heavily soiled crate liners and waterproof beds. 24-hour turnaround.",
    address: " Kallang",
    priceFrom: "$15/kg",
    website: "https://petlaundry.sg",
    phone: "+65 6244 5520",
  },
  {
    name: "Country Boarding by Annie",
    category: "Boarding",
    blurb:
      "Annie hosts 6 dogs at a time in her landed home with a large garden. Daily walks, photo updates, no kennels.",
    address: " Lim Chu Kang",
    priceFrom: "$55/night",
    website: "https://countryboarding.sg",
    phone: "+65 9888 3401",
  },
  {
    name: "The Wagington Hotel & Resort",
    category: "Boarding",
    blurb:
      "Boutique hotel suites with private patios. Webcam access, daily grooming, and pool sessions for water-lovers.",
    address: " Cluny Court",
    priceFrom: "$95/night",
    website: "https://wagington.com",
    phone: "+65 6471 5152",
  },
  {
    name: "Sembawang Senior Pet Stay",
    category: "Boarding",
    blurb:
      "Specialised in older and medical-needs dogs. Quiet rooms, soft bedding, ex-vet-tech overnight on duty.",
    address: " Sembawang",
    priceFrom: "$70/night",
    website: "https://seniorpetstay.sg",
    phone: "+65 6555 0142",
  },
  {
    name: "The Patient Groomer",
    category: "Grooming",
    blurb:
      "One dog at a time, no cages, no dryers if your dog hates them. Specialises in anxious and elderly pups.",
    address: " Tanjong Pagar",
    priceFrom: "$80",
    website: "https://patientgroomer.sg",
    phone: "+65 9221 7700",
  },
  {
    name: "Soapy Tails Mobile Grooming",
    category: "Grooming",
    blurb:
      "Self-contained grooming van comes to your block. Hydrobath, hand-finished cuts, quiet clippers.",
    address: " Mobile, islandwide",
    priceFrom: "$95",
    website: "https://soapytails.sg",
    phone: "+65 8123 9090",
  },
  {
    name: "Bishan Tail & Trim",
    category: "Grooming",
    blurb:
      "Neighbourhood favourite by groomer Helen. Walk-in nail trims, breed-standard cuts, gentle senior packages.",
    address: " Bishan",
    priceFrom: "$55",
    website: "https://tailtrim.sg",
    phone: "+65 6258 4488",
  },
];

const DOG_RUNS = [
  {
    sortOrder: 1,
    name: "Bishan-Ang Mo Kio Park Dog Run (It consists of two parts)",
    area: " Central",
    size: "Approximately 240 Sqm",
    description: "",
    address: "453 Ang Mo Kio Ave 1, Singapore 569972",
    openingHours: "24/7",
  },
  {
    sortOrder: 2,
    name: "Toa Payoh Dog Run Park",
    area: "Central",
    size: "Approximately 420 Sqm",
    description: "",
    address: "Toa Payoh Lorong 1 near Blk 128.",
    openingHours: "7am - 9pm",
  },
  {
    sortOrder: 3,
    name: "Potong Pasir Dog Run",
    area: "Central",
    size: "approximately: 850 Sqm",
    description: "",
    address: "Potong Pasir Ave 3, S357682",
  },
  {
    sortOrder: 4,
    name: "Tiong Bahru Dog Run Park",
    area: "Central",
    size: "approximately 2,100 Sqm",
    description: "",
    address: "1 Henderson Rd, Singapore 15956",
  },
  {
    sortOrder: 5,
    name: "East Coast Dog Run Park",
    area: "East",
    size: "Approximately 400 square meters",
    description: "",
    address: "Parkland Green, East Coast Park Service Rd, Singapore 449875",
  },
  {
    sortOrder: 6,
    name: "Bedok Town Park Dog Run",
    area: "East",
    size: "Approximately 500–600 square meters",
    description: "",
    address: "* Bedok Town Park, along Bedok North Road.",
    openingHours: "Open 24 hours daily",
  },
  {
    sortOrder: 7,
    name: "Pasir Ris Park Dog Run",
    area: "East",
    size: "~ Approximately 800 sqm",
    description: "",
    address: "125 Pasir Ris Rd (Near Carpark E).",
    openingHours: "24/7",
  },
  {
    sortOrder: 8,
    name: "Telok Kurau Dog Run",
    area: "East",
    size: "~ Approximately 400–500 Sqm",
    description: "",
    address:
      "Telok Kurau Park, located at the junction of Telok Kurau Lorong N and Lorong M.",
    openingHours: "24/7",
  },
  {
    sortOrder: 9,
    name: "Tampines Boulevard Park Dog Run",
    area: "East",
    size: "Approximately 1,200 sqm",
    description: "",
    address: "Along Tampines Ave 12.",
    openingHours: "24/7",
  },
  {
    sortOrder: 10,
    name: "Katong Park Dog Run Park",
    area: "East",
    size: "Approximately 150 sqm (Small/Cozy)",
    description: "",
    address: "Junction of Meyer Road and Fort Road.",
    openingHours: "24/7 (Lights until 10 PM)",
  },
  {
    sortOrder: 11,
    name: "Lengkong Enam Interim Park Dog Run",
    area: "East",
    size: "Approximately 1,000 sqm",
    description: "",
    address: "Along Jalan Selamat and Lengkong Tujuh.",
    openingHours: "24/7",
  },
  {
    sortOrder: 12,
    name: "Mariam Way Dog Run Park",
    area: "East",
    size: "Approximately 300 sqm",
    description: "",
    address: "Mariam Way Playground.",
    openingHours: "24/7",
  },
  {
    sortOrder: 13,
    name: "Opera Estate Dog Run",
    area: "East",
    size: "Approximately 300–400 Sqm",
    description: "",
    address:
      "Located at Opera Estate Football Field, along Swan Lake Avenue (near the junction of Fidelio Street), Singapore 455707.",
    openingHours: "Open 24 hours daily",
  },
  {
    sortOrder: 14,
    name: "Koon Seng Park Dog Run",
    area: "East",
    size: "Approximately 250-300 Sqm",
    description: "",
    address:
      "Located within Koon Seng Park, at the junction of Koon Seng Road and Joo Chiat Lane, Singapore 427013.",
    openingHours: "Open 24 hours daily",
    image: "koon-seng.png",
  },
  {
    sortOrder: 15,
    name: "Guillemard Road Open Space Dog Run",
    area: "East",
    size: "Approximately 300–400 Sqm",
    description: "",
    address:
      "Located at the junction of Guillemard Road and Lorong 22 Geylang (opposite the former Guillemard Camp area).",
    openingHours: "Open 24 hours daily",
  },
  {
    sortOrder: 16,
    name: "Sembawang Dog Run Park",
    area: "North",
    size: "Approximately 2,700 sqm",
    description: "",
    address: "Northern end of Sembawang Road.",
    openingHours: "24/7 (No dedicated lighting)",
  },
  {
    sortOrder: 17,
    name: "Yishun Park Dog Run",
    area: "North",
    size: "Approximately 500 sqm",
    description: "",
    address: "Yishun Central (Opposite Adora Green). Hours: 24/7.",
  },
  {
    sortOrder: 18,
    name: "Punggol Waterway Park Dog Run",
    area: "North-East",
    size: "Approximately 500 sqm",
    description: "",
    address: "Sentul Crescent. Hours: 24/7.",
  },
  {
    sortOrder: 19,
    name: "Rivervale Dog Run (Sengkang)",
    area: "North-East",
    size: "Approximately 450 sqm",
    description: "",
    address: "Near Block 178 Rivervale Crescent. Hours: 7:00 AM – 10:00 PM.",
  },
  {
    sortOrder: 20,
    name: "Woodlands Waterfront Dog Run",
    area: "North",
    size: "Approximately 600 sqm",
    description: "",
    address: "Admiralty Road West. Hours: 24/7.",
  },
  {
    sortOrder: 21,
    name: "K9 Park @ NEX (Mall Dog Run)",
    area: "North-East",
    size: "Approximately 180 sqm",
    description: "",
    address: "23 Serangoon Central, NEX Level 4R",
    openingHours: "10:30 AM – 10:30 PM",
  },
  {
    sortOrder: 22,
    name: "Sun Plaza Park Dog Run",
    area: "East",
    size: "Approximately 600 sqm",
    description: "",
    address:
      "Tampines Avenue 7 and Tampines Avenue 9, Singapore 520558. (The dog run is situated closer to the Tampines Regional Library and the Tampines Eco Green entrance side of the park).",
    openingHours: "24/7",
  },
  {
    sortOrder: 23,
    name: "West Coast Park Dog Run",
    area: "West",
    size: "Massive (Part of the 50-hectare park)",
    description: "",
    address: "Parallel to West Coast Highway (Near Carpark 1).",
    openingHours: "24/7 (Lights until 7 PM)",
  },
  {
    sortOrder: 24,
    name: "Clementi Woods Park Dog Run",
    area: "West",
    size: "Approximately 4,000 sqm",
    description: "",
    address: "152 West Coast Road (next to West Coast Plaza).",
    openingHours: "24/7 (Lights until 7 AM)",
  },
  {
    sortOrder: 25,
    name: "Jurong Lake Gardens Dog Run",
    area: "West",
    size: "Approximately 2,200 sqm",
    description: "",
    address: "104 Yuan Ching Road.",
    openingHours: "8:00 AM – 10:00 PM",
  },
  {
    sortOrder: 26,
    name: "Bukit Gombak Park Dog Run",
    area: "West",
    size: "Approximately 400 sqm",
    description: "",
    address: "Bukit Batok West Ave 5.",
    openingHours: "24/7",
  },
  {
    sortOrder: 27,
    name: "Villa Verde Park Dog Run",
    area: "West",
    size: "Approximately 400-500 Sqm",
    description: "",
    address:
      "Located within Villa Verde Park, at the end of Verde View, Singapore 688644 (along the Pang Sua Park Connector)",
    openingHours: "Open 24 hours daily",
  },
];

export const seedDogRuns = internalMutation({
  handler: async (ctx) => {
    const existing = await ctx.db.query("dogRuns").collect();
    if (existing.length > 0) return "Dog runs already seeded.";
    for (const run of DOG_RUNS) {
      await ctx.db.insert("dogRuns", { waterPoint: false, ...run });
    }
    return `Seeded ${DOG_RUNS.length} dog runs.`;
  },
});

export const seedServices = internalMutation({
  handler: async (ctx) => {
    const existing = await ctx.db.query("services").collect();
    if (existing.length > 0) return "Services already seeded.";
    for (const svc of SERVICES) {
      await ctx.db.insert("services", { featured: false, ...svc });
    }
    return `Seeded ${SERVICES.length} services.`;
  },
});

const BLOG_POSTS = [
  {
    category: "Adoption Story",
    title: "Mochi finds a quiet flat in Tiong Bahru",
    date: "12 May 2026",
    author: "Aishah, foster carer",
    cover: "https://placedog.net/800/500?id=401",
    excerpt:
      "After three months in foster, our shy little Shih Tzu mix finally has a corner of her own. We visited her new family last weekend — and yes, she still squeaks when you scratch her chin.",
    readTime: "4 min read",
    body: `<p>For her first eight weeks in foster, Mochi lived under my dining table. Not beside it — under it, behind a curtain of chair legs, where she could see the room without the room seeing her.</p>
<p>She came to us from a hoarding case in the north of the island: one of fourteen dogs in a two-room flat, none of them socialised, all of them frightened of hands. Mochi was the smallest and the quietest, and for a long time we worried that quiet was all she had left.</p>
<h2>The squeak</h2>
<p>The turning point, as it often is, was nonsense. One evening I scratched her chin and she let out a single, indignant squeak — half hiccup, half protest. It was the first sound she'd made that wasn't fear. I froze. She did it again. Within a week she was following me to the kitchen, squeaking the whole way, as if narrating.</p>
<p>That squeak is now famous. Her adopters — a retired couple in a quiet Tiong Bahru walk-up — heard it at our open day and were, in their own words, "completely finished." They'd come to meet a different dog entirely.</p>
<h2>Home</h2>
<p>We visited last weekend. Mochi has a basket by the window, a strict 7am breakfast appointment, and a corner of the sofa that is understood by all parties to be hers. She still hides when the doorbell rings. But she comes out again — and she still squeaks when you scratch her chin.</p>`,
  },
  {
    category: "Guidelines",
    title: "What HDB approval actually means for your dog",
    date: "06 May 2026",
    author: "Homeward Team",
    cover: "https://placedog.net/800/500?id=402",
    excerpt:
      "A plain-English guide to Project ADORE, the Mixed Breed Scheme, and the height and weight rules that decide which dogs can call an HDB flat home. With examples and what to do if you're unsure.",
    readTime: "7 min read",
    body: `<p>"HDB-approved" is one of the most misunderstood phrases in Singapore dog adoption. People treat it like a single stamp of approval, when in reality it's a set of overlapping rules — and knowing the difference is what decides whether a dog can legally call a flat home.</p>
<h2>Project ADORE, in plain English</h2>
<p>Project ADORE (ADoption and REhoming of dogs) is a scheme that allows certain larger local mixed-breed dogs to be kept in HDB flats, provided they meet specific conditions and the dog is sourced through an approved partner. It exists precisely because the default HDB rules were designed around small breeds and excluded most rescue dogs.</p>
<p>Under ADORE, an adopted dog must be microchipped, sterilised, licensed, and — importantly — under a height and weight cap measured at the shoulder.</p>
<h2>The Mixed Breed Scheme</h2>
<p>Separately, HDB permits a list of approved small breeds and, through the Mixed Breed Scheme, local Singapore Specials that fall within the size limits. The practical effect: a 15kg Singapore Special may qualify where a purebred of the same size does not.</p>
<h2>What to do if you're unsure</h2>
<p>Don't guess. Before committing to a dog, ask the welfare group three things: is this dog ADORE-eligible, what is its adult height and weight, and will they support the licensing paperwork. A responsible group will have answers ready — and if they don't, that tells you something too.</p>`,
  },
  {
    category: "Adoption Story",
    title: "Biscuit's first year on a sofa",
    date: "28 Apr 2026",
    author: "Marcus, adopter",
    cover: "https://placedog.net/800/500?id=403",
    excerpt:
      "A Singapore Special who spent four years in a back lane is now hogging the air-con and judging the neighbours. We catch up with Biscuit and his adopter, twelve months on.",
    readTime: "6 min read",
    body: `<p>Biscuit spent the first four years of his life in a back lane in the west of Singapore, surviving on scraps and the kindness of one hawker who left water out. When we trapped him for sterilisation, he was so flat against the ground he looked like a shadow that had given up.</p>
<h2>Twelve months later</h2>
<p>Today Biscuit is hogging the air-con in a Clementi flat, sleeping on his back with all four legs in the air, and — according to his adopter Marcus — "judging the neighbours through the window like a retired magistrate."</p>
<p>"The first month was hard," Marcus admits. "He didn't know what a sofa was for. He didn't know what to do with a toy. He flinched at brooms." Singapore Specials carry their street years with them, and decompression takes time.</p>
<h2>What changed</h2>
<p>Routine, mostly. The same walk at the same time. The same words. Marcus didn't force affection — he just made the flat a place where nothing bad ever happened, over and over, until Biscuit believed it.</p>
<p>"I didn't rescue him," Marcus says. "I just provided the air-con. He did the rest."</p>`,
  },
  {
    category: "Guidelines",
    title: "Your first 30 days with a rescue dog",
    date: "19 Apr 2026",
    author: "Dr. Lim, partner vet",
    cover: "https://placedog.net/800/500?id=404",
    excerpt:
      "The 3-3-3 rule, decompression, the vet visit timeline, and what to actually do (and not do) in the first month. Required reading for new adopters.",
    readTime: "9 min read",
    body: `<p>The first month with a rescue dog is the one that matters most — and the one most new adopters get wrong, usually out of love. Here's the framework we give every adopter before they take a dog home.</p>
<h2>The 3-3-3 rule</h2>
<p>Three days to decompress. Three weeks to learn your routine. Three months to start feeling at home. In the first three days, expect your dog to be overwhelmed, possibly shut down, possibly not eating much. This is normal. Do less, not more.</p>
<h2>Decompression</h2>
<p>Resist the urge to introduce your new dog to everyone you know. No parties, no dog cafés, no big walks on day one. Give them a small, safe space and let them choose when to explore it. A dog that hides is not a sad dog — it's a sensible one.</p>
<h2>The vet visit</h2>
<p>Book a wellness check within the first week, but don't make it day one unless there's an emergency. You want the first car ride and the first vet to come after a little trust has formed, not before.</p>
<h2>What not to do</h2>
<p>Don't bathe them immediately. Don't take the collar off outdoors. Don't punish fear. And don't panic if week one looks nothing like the dog you met at the shelter — you're meeting the real one now, and they're meeting you.</p>`,
  },
  {
    category: "Tips",
    title: "Walking your dog in Singapore's heat",
    date: "11 Apr 2026",
    author: "Homeward Team",
    cover: "https://placedog.net/800/500?id=405",
    excerpt:
      "Pavement temperature, hydration, the seven-second tarmac test, and the best times to go out without melting your dog. A short, hot-weather field guide.",
    readTime: "5 min read",
    body: `<p>Singapore's pavements can hit 50°C on a sunny afternoon. Your dog walks on those pavements barefoot. The maths is not in their favour, and heatstroke in dogs can turn fatal faster than most owners expect.</p>
<h2>The seven-second test</h2>
<p>Before any walk, press the back of your hand flat against the pavement for seven seconds. If you can't hold it there comfortably, it's too hot for paws. Simple, free, and it has saved more pads than any product on the market.</p>
<h2>Timing</h2>
<p>Walk before 8am or after 7pm. The midday sun isn't just uncomfortable — it's dangerous, especially for flat-faced breeds and seniors who can't cool themselves efficiently. A shorter walk in the cool is worth more than a long one in the heat.</p>
<h2>Hydration and warning signs</h2>
<p>Carry water on every outing. Watch for heavy panting, drooling, bright red gums, and stumbling — these are early heatstroke signs. If you see them, move to shade, wet the paws and belly with cool (not ice-cold) water, and call your vet immediately.</p>`,
  },
  {
    category: "Adoption Story",
    title: "Pepper, the senior schnauzer, picks her person",
    date: "02 Apr 2026",
    author: "Aishah, foster carer",
    cover: "https://placedog.net/800/500?id=406",
    excerpt:
      "Some dogs choose their family. Pepper walked past six prospective adopters at our open day and sat on the seventh's foot. The rest, as they say, is history.",
    readTime: "5 min read",
    body: `<p>People assume adopters choose dogs. Anyone who's worked an open day knows it's often the other way around.</p>
<h2>The open day</h2>
<p>Pepper is an eleven-year-old schnauzer surrendered when her elderly owner moved into care. Senior dogs are the hardest to rehome — everyone wants a puppy, few want grey muzzles and vet bills. We braced ourselves for a long wait.</p>
<p>At our April open day, six prospective adopters knelt down to greet her. Pepper walked past every one of them — polite but unmoved — and sat squarely on the seventh person's foot. Then she leaned her whole weight against their shin and sighed.</p>
<h2>The seventh person</h2>
<p>That person hadn't even come for a dog. They'd driven a friend to the event. They left having filled in an adoption form, slightly dazed, asking us what senior dogs eat.</p>
<p>Pepper's been home three weeks now. She sleeps eighteen hours a day, supervises dinner preparation, and still picks her person — following them room to room, sitting on the same foot, every evening.</p>`,
  },
  {
    category: "Guidelines",
    title: "Fostering 101: what we're actually asking",
    date: "24 Mar 2026",
    author: "Homeward Team",
    cover: "https://placedog.net/800/500?id=407",
    excerpt:
      "Fostering isn't permanent adoption — but it's also not babysitting. A clear breakdown of the time, money and emotional commitment of being a foster carer, and why we need more of them.",
    readTime: "8 min read",
    body: `<p>Every welfare group in Singapore is short on the same thing: foster homes. And every group hears the same hesitations. So let's be clear about what fostering actually is — and isn't.</p>
<h2>It isn't permanent</h2>
<p>Fostering is temporary care for a dog between rescue and adoption. You're not committing to keep the dog forever — you're giving them a home environment to decompress, learn house manners, and become adoptable. Most fosters last a few weeks to a few months.</p>
<h2>It isn't babysitting</h2>
<p>But it's also real work. A foster dog may not be toilet-trained. They may have medical needs, fear of stairs, separation anxiety, or no idea how to be alone. You're not minding a pet — you're rehabilitating one. The group covers vet costs and supplies; you provide the patience.</p>
<h2>Why we need you</h2>
<p>A dog in foster is a dog out of a kennel — calmer, healthier, and far more likely to be adopted because we can finally tell adopters how they behave in a home. Every foster home opens a kennel for the next dog off the street. The maths is brutal and simple: more fosters, more lives.</p>`,
  },
  {
    category: "Tips",
    title: "Introducing your rescue to a resident pet",
    date: "15 Mar 2026",
    author: "Dr. Lim, partner vet",
    cover: "https://placedog.net/800/500?id=408",
    excerpt:
      "Slow, neutral, no eye contact. A step-by-step plan for the first week of dog-to-dog and dog-to-cat introductions, with the warning signs to watch for.",
    readTime: "6 min read",
    body: `<p>Bringing a rescue dog into a home that already has a pet is where many adoptions wobble. Done slowly, it works almost every time. Done in a hurry, it can sour a relationship before it begins.</p>
<h2>The three rules</h2>
<p>Slow. Neutral. No eye contact. Write them on your hand if you have to. The instinct to "just let them meet and sort it out" is the single most common mistake we see.</p>
<h2>Day by day</h2>
<p>Start with scent only — swap blankets between the resident pet and the newcomer before they ever meet. Then parallel walks on neutral ground, several metres apart, no forced interaction. Let them exist near each other before they interact with each other.</p>
<p>For dog-to-cat introductions, the cat must always have an escape route and high ground. Never trap either animal in a corner to "get it over with."</p>
<h2>Warning signs</h2>
<p>Stiff bodies, hard stares, raised hackles, and frozen stillness are all signals to calmly increase distance. Growling is communication, not failure — it's the warning before the bite, and a dog that's allowed to growl is a dog telling you what it needs.</p>`,
  },
];

export const seedBlogPosts = internalMutation({
  handler: async (ctx) => {
    const existing = await ctx.db.query("blogPosts").collect();
    if (existing.length > 0) return "Blog posts already seeded.";
    for (const post of BLOG_POSTS) {
      await ctx.db.insert("blogPosts", post);
    }
    return `Seeded ${BLOG_POSTS.length} blog posts.`;
  },
});
