// Dog runs around Singapore
window.DOGRUNS = [
  {
    id: 1,
    name: "Bishan-Ang Mo Kio Dog Run",
    address: "1382 Ang Mo Kio Ave 1",
    hours: "Open 24 hours",
    image: "https://placedog.net/600/400?id=301",
    size: "Large",
  },
  {
    id: 2,
    name: "West Coast Park Dog Run",
    address: "West Coast Ferry Rd",
    hours: "Open 24 hours",
    image: "https://placedog.net/600/400?id=302",
    size: "Large",
  },
  {
    id: 3,
    name: "Tampines Eco Green Dog Run",
    address: "Tampines Ave 12",
    hours: "7am – 7pm daily",
    image: "https://placedog.net/600/400?id=303",
    size: "Medium",
  },
  {
    id: 4,
    name: "Katong Park Dog Run",
    address: "Meyer Rd, Katong",
    hours: "Open 24 hours",
    image: "https://placedog.net/600/400?id=304",
    size: "Small",
  },
  {
    id: 5,
    name: "Punggol Promenade Dog Run",
    address: "Punggol Pt Walk",
    hours: "Open 24 hours",
    image: "https://placedog.net/600/400?id=305",
    size: "Medium",
  },
  {
    id: 6,
    name: "Tiong Bahru Park Dog Run",
    address: "Henderson Rd, Tiong Bahru",
    hours: "5am – 11pm daily",
    image: "https://placedog.net/600/400?id=306",
    size: "Medium",
  },
  {
    id: 7,
    name: "Jurong Lake Gardens Dog Run",
    address: "Yuan Ching Rd, Jurong",
    hours: "Open 24 hours",
    image: "https://placedog.net/600/400?id=307",
    size: "Large",
  },
  {
    id: 8,
    name: "Bedok Reservoir Dog Run",
    address: "Bedok Reservoir Rd",
    hours: "Open 24 hours",
    image: "https://placedog.net/600/400?id=308",
    size: "Medium",
  },
  {
    id: 9,
    name: "Sengkang Riverside Dog Run",
    address: "Anchorvale St, Sengkang",
    hours: "Open 24 hours",
    image: "https://placedog.net/600/400?id=309",
    size: "Small",
  },
  {
    id: 10,
    name: "Pasir Ris Central Dog Run",
    address: "Pasir Ris Central, Blk 738",
    hours: "6am – 10pm daily",
    image: "https://placedog.net/600/400?id=310",
    size: "Small",
  },
  {
    id: 11,
    name: "East Coast Park Dog Run",
    address: "East Coast Park, Area E",
    hours: "Open 24 hours",
    image: "https://placedog.net/600/400?id=311",
    size: "Large",
  },
  {
    id: 12,
    name: "Hong Lim Park Dog Run",
    address: "Upper Pickering St",
    hours: "5am – 11pm daily",
    image: "https://placedog.net/600/400?id=312",
    size: "Small",
  },
];
