// Dog adoption data
window.DOGS = [
  { id: 1,  name: "Mochi",   breed: "Shih Tzu Mix",       age: "3 yrs",  birthday: "12 Mar 2023", gender: "F", hdb: true,  photo: 1,
    about: "Mochi was found wandering the back lanes of Tiong Bahru as a puppy. She's blossomed into a calm, observant little soul who loves quiet mornings, slow cuddles and a good window seat. Excellent with children and unbothered by visitors." },
  { id: 2,  name: "Biscuit", breed: "Singapore Special",  age: "5 yrs",  birthday: "08 Jul 2021", gender: "M", hdb: false, photo: 5,
    about: "Biscuit is a classic Singapore Special — long legs, kind eyes, opinions about cats. He's spent the last two years in foster learning to trust again, and is ready for a landed home with a patient adult-only family." },
  { id: 3,  name: "Rusty",   breed: "Jack Russell",       age: "2 yrs",  birthday: "21 Oct 2023", gender: "M", hdb: true,  photo: 10,
    about: "All terrier, all the time. Rusty has the energy of a small jet engine and the focus of a Zen monk when he's working a chew toy. Best for an active home that can give him two walks a day." },
  { id: 4,  name: "Luna",    breed: "Border Collie Mix",  age: "4 yrs",  birthday: "02 Feb 2022", gender: "F", hdb: false, photo: 15,
    about: "Luna is the smartest dog at the shelter and she knows it. Knows seven cues, is learning agility, and would thrive with someone who likes structured training games and long Sunday hikes." },
  { id: 5,  name: "Pepper",  breed: "Miniature Schnauzer",age: "6 yrs",  birthday: "14 May 2020", gender: "F", hdb: true,  photo: 20,
    about: "Pepper is a perfectly groomed little professor — eyebrows for days, opinions about strangers, devotion for one person. She's looking for a quiet single-person home where she can be the only pet." },
  { id: 6,  name: "Bandit",  breed: "Singapore Special",  age: "7 yrs",  birthday: "30 Aug 2019", gender: "M", hdb: false, photo: 25,
    about: "Bandit is our gentle giant, mellowed by years and a hundred handlers. He'd be the perfect first dog for a family with older kids — calm, treat-motivated, never reactive." },
  { id: 7,  name: "Daisy",   breed: "Maltese",            age: "1 yr",   birthday: "05 Apr 2025", gender: "F", hdb: true,  photo: 30,
    about: "Daisy is a year-old bundle of white floof who's still figuring out the world. She loves being carried, hates the rain, and falls asleep on whoever is sitting closest." },
  { id: 8,  name: "Hugo",    breed: "Beagle",             age: "4 yrs",  birthday: "19 Jun 2022", gender: "M", hdb: false, photo: 35,
    about: "Hugo has a beagle's nose and a beagle's appetite — which is to say, both are legendary. He'd love a home with a garden to sniff and another playful dog to keep him company." },
  { id: 9,  name: "Olive",   breed: "Poodle Mix",         age: "2 yrs",  birthday: "11 Nov 2023", gender: "F", hdb: true,  photo: 40,
    about: "Olive is a hypoallergenic charmer who came to us after her elderly owner passed. She knows house manners, walks beautifully on leash, and just wants a lap to be on." },
  { id: 10, name: "Coco",    breed: "Toy Poodle",         age: "8 yrs",  birthday: "23 Jan 2018", gender: "F", hdb: true,  photo: 45,
    about: "Coco is a senior lady looking for a soft retirement. She does best in a calm flat, sleeps about 18 hours a day, and has never once met a couch she didn't like." },
  { id: 11, name: "Bruno",   breed: "Labrador Mix",       age: "3 yrs",  birthday: "16 Sep 2022", gender: "M", hdb: false, photo: 50,
    about: "Bruno is 32 kilos of pure golden enthusiasm. He's water-mad, treat-mad, and will be your best friend within seven seconds. Needs space to run." },
  { id: 12, name: "Suki",    breed: "Shiba Inu Mix",      age: "5 yrs",  birthday: "27 Dec 2020", gender: "F", hdb: false, photo: 55,
    about: "Suki is independent, sharp, and selective with her affection — but loyal as anything once you're in. Best as the only pet, ideally with a quiet adult household." },
  { id: 13, name: "Theo",    breed: "Chihuahua",          age: "9 yrs",  birthday: "04 Mar 2017", gender: "M", hdb: true,  photo: 60,
    about: "Theo is a tiny old man who has been waiting two years for a home. He'd love a soft jumper, a heated bed, and one human to follow around devotedly." },
  { id: 14, name: "Sage",    breed: "Singapore Special",  age: "4 yrs",  birthday: "18 May 2022", gender: "F", hdb: false, photo: 65,
    about: "Sage came to us terrified and is now blossoming. She's gentle, watchful, and quick to learn — looking for a calm landed home and someone willing to take it slow." },
  { id: 15, name: "Milo",    breed: "Bichon Frise",       age: "2 yrs",  birthday: "09 Aug 2023", gender: "M", hdb: true,  photo: 70,
    about: "Milo is a small white cloud with very specific opinions about which toys are acceptable. Hypoallergenic, house-trained, and excellent with everyone he meets." },
  { id: 16, name: "Penny",   breed: "Corgi Mix",          age: "6 yrs",  birthday: "25 Feb 2020", gender: "F", hdb: false, photo: 75,
    about: "Penny has the legs of a corgi and the soul of a labrador. She's friendly, food-motivated, and would love a home where she can be involved in everything — including the laundry." },
  { id: 17, name: "Otis",    breed: "Golden Retriever",   age: "7 yrs",  birthday: "07 Jul 2019", gender: "M", hdb: false, photo: 80,
    about: "Otis is a senior gentleman with grey on his muzzle and softness in his eyes. He's been with us six months and we'd love to see him in a sofa-equipped landed home for his golden years." },
  { id: 18, name: "Nala",    breed: "Pomeranian",         age: "3 yrs",  birthday: "13 Oct 2022", gender: "F", hdb: true,  photo: 85,
    about: "Nala is three kilos of personality. She prances, she poses, she patrols the kitchen. Best in a home without small children — she likes her space." },
  { id: 19, name: "Archie",  breed: "Cocker Spaniel",     age: "5 yrs",  birthday: "01 Jun 2021", gender: "M", hdb: false, photo: 90,
    about: "Archie has the most beautiful spaniel ears and the most beautiful spaniel patience. He's a true family dog — gentle with kids, calm around cats, ready to be loved." },
  { id: 20, name: "Ruby",    breed: "Cavalier King Charles", age: "4 yrs", birthday: "20 Apr 2022", gender: "F", hdb: true,  photo: 95,
    about: "Ruby is exactly as sweet as she looks. A perfect companion dog — soft, social, and entirely uninterested in causing any kind of trouble whatsoever." },
  { id: 21, name: "Finn",    breed: "Singapore Special",  age: "6 yrs",  birthday: "15 Nov 2019", gender: "M", hdb: false, photo: 100,
    about: "Finn is a handsome, leggy mongrel who's been overlooked too many times. He's quiet, dignified, and would thrive with a calm adult who appreciates the strong silent type." },
  { id: 22, name: "Maple",   breed: "Dachshund",          age: "2 yrs",  birthday: "28 Sep 2023", gender: "F", hdb: true,  photo: 105,
    about: "Maple is a sausage with attitude. She's stubborn, hilarious, and entirely convinced she's a big dog. Best in a home that thinks her opinions are charming." },
  { id: 23, name: "Diesel",  breed: "Mixed Breed",        age: "8 yrs",  birthday: "10 Jan 2018", gender: "M", hdb: false, photo: 110,
    about: "Diesel is our shelter elder statesman. Slow walks, soft beds, a cool tile floor — that's all he asks. He'd love to spend his last few chapters with someone kind." },
  { id: 24, name: "Willow",  breed: "Yorkshire Terrier",  age: "5 yrs",  birthday: "06 Mar 2021", gender: "F", hdb: true,  photo: 115,
    about: "Willow is a tiny, tough little Yorkie with the heart of a guard dog. She's protective of her people and friendly to those she trusts. Looking for a quieter household." },
];

window.FINEPRINT = [
  "House-trained, loves long walks at East Coast.",
  "A little shy at first, completely devoted once she trusts you.",
  "Knows sit, stay, paw. Working on \u201cleave it.\u201d",
  "Best as the only dog in the home.",
  "Great with kids over 8. Calm around babies.",
  "Loves car rides and rolling in fresh laundry.",
  "Needs a patient owner \u2014 still learning the world.",
  "Fully vaccinated, sterilised, microchipped.",
  "Currently in foster in Tampines. Visits by appointment.",
  "Quiet apartment dog. Sleeps through the night.",
  "Cuddles first, eats second. Always.",
  "Walks beautifully on leash. No pulling.",
  "Affectionate with everyone she meets, including the postman.",
  "Would thrive with another playful dog at home.",
  "Senior gentleman looking for a soft sofa.",
  "Recovered from a rough start \u2014 now thriving.",
  "Crate-trained. Travels well.",
  "Loves squeaky toys, hates the vacuum.",
  "Food-motivated. Will work for cheese.",
  "Best suited to a ground-floor home with a garden.",
  "Needs a daily walk and a daily nap. In that order.",
  "Gets along with cats after slow introductions.",
  "Will follow you from room to room. Velcro dog.",
  "Big personality in a small package.",
  "Calm, easygoing, perfect first dog.",
  "Loves the beach. Tolerates the bath.",
  "Talks back when ignored. Very expressive.",
  "Smart, sensitive, slightly dramatic.",
  "Foster says: \u201cThe sweetest dog I\u2019ve ever met.\u201d",
  "Looking for a forever, not a maybe.",
];
