// Event data — pet adoption events, fairs, etc.
window.EVENTS = [
  {
    id: 1,
    title: "Spring Adoption Drive",
    kind: "Adoption",
    banner: "https://placedog.net/1200/600?id=200",
    location: "Bishan Park Pavilion, Hall A",
    dateLine: "5 Apr 2026 to 6 Apr 2026, 8am to 9pm daily",
    short: "Meet 30+ rescue dogs over one weekend. On-site adoption counsellors, free goodie bags, and a quiet room for shy doggos to mingle slowly with prospective families.",
    cta: "Reserve a slot",
    tag: "Featured",
  },
  {
    id: 2,
    title: "Homeward Annual Pet Fair",
    kind: "Pet Fair",
    banner: "https://placedog.net/1200/600?id=210",
    location: "Suntec Convention Hall 401",
    dateLine: "17 May 2026, 10am to 7pm",
    short: "Our biggest day of the year. 40+ small businesses, vet talks, training demos, paw-print art for the kids, and a live shelter dog showcase every hour on the hour.",
    cta: "Get tickets",
  },
  {
    id: 3,
    title: "Microchip &amp; Vaccination Day",
    kind: "Clinic",
    banner: "https://placedog.net/1200/600?id=220",
    location: "Mt Pleasant Vet, Whitley Road",
    dateLine: "22 Jun 2026, 9am to 1pm",
    short: "Subsidised microchipping ($15) and core vaccinations ($40) for adopted dogs and Singapore Specials. By appointment — limited to 60 slots.",
    cta: "Book a slot",
  },
  {
    id: 4,
    title: "Sunset Sembawang Walk",
    kind: "Community",
    banner: "https://placedog.net/1200/600?id=230",
    location: "Sembawang Park Boardwalk",
    dateLine: "12 Jul 2026, 5pm to 7pm",
    short: "A monthly community walk for adopters, fosters and curious dog-lovers. Bring water, bring your dog, bring a friend who's been thinking about adopting.",
    cta: "RSVP",
  },
  {
    id: 5,
    title: "Senior Dogs Meet &amp; Greet",
    kind: "Adoption",
    banner: "https://placedog.net/1200/600?id=240",
    location: "Homeward Shelter, Sembawang",
    dateLine: "3 Aug 2026 to 4 Aug 2026, 11am to 5pm daily",
    short: "Eight of our older residents need quiet homes for their best years yet. Drop by for a slow afternoon, a cup of tea, and the company of a very good old dog.",
    cta: "Plan your visit",
  },
  {
    id: 6,
    title: "Foster Carer Workshop",
    kind: "Training",
    banner: "https://placedog.net/1200/600?id=250",
    location: "Homeward Shelter, Sembawang",
    dateLine: "14 Sep 2026, 2pm to 5pm",
    short: "Considering becoming a foster carer? Spend an afternoon with our team learning the basics — feeding, decompression, vet visits, and how to say goodbye.",
    cta: "Sign up free",
  },
];
