// Singapore animal welfare groups
window.GROUPS = [
  {
    id: 1,
    name: "SOSD — Save Our Street Dogs",
    blurb: "Singapore Specials. Sanctuary in Jalan Bahar.",
    image: "https://placedog.net/300/300?id=501",
    dogsAvailable: 86,
    email: "adopt@sosd.org.sg",
    website: "https://sosd.org.sg",
    facebook: "https://facebook.com/sosd.sg",
    instagram: "https://instagram.com/sosd_sg",
    tiktok: "https://tiktok.com/@sosd.sg",
    youtube: "https://youtube.com/@sosdsingapore",
  },
  {
    id: 2,
    name: "Action for Singapore Dogs",
    blurb: "Rescue, rehab, rehome. Since 2000.",
    image: "https://placedog.net/300/300?id=502",
    dogsAvailable: 52,
    email: "adopt@asdsingapore.com",
    website: "https://asdsingapore.com",
    facebook: "https://facebook.com/ActionForSingaporeDogs",
    instagram: "https://instagram.com/asd_singapore",
  },
  {
    id: 3,
    name: "Causes for Animals (Singapore)",
    blurb: "Community cats &amp; rescue dogs.",
    image: "https://placedog.net/300/300?id=503",
    dogsAvailable: 34,
    email: "hello@causesforanimals.com",
    website: "https://causesforanimals.com",
    facebook: "https://facebook.com/CausesForAnimalsSG",
    instagram: "https://instagram.com/causesforanimals",
    youtube: "https://youtube.com/@causesforanimals",
  },
  {
    id: 4,
    name: "Voices for Animals",
    blurb: "Senior dogs &amp; long-stayers.",
    image: "https://placedog.net/300/300?id=504",
    dogsAvailable: 41,
    email: "adopt@voicesforanimals.com.sg",
    website: "https://voicesforanimals.com.sg",
    facebook: "https://facebook.com/voicesforanimalssg",
    instagram: "https://instagram.com/voicesforanimalssg",
    tiktok: "https://tiktok.com/@voicesforanimals",
  },
  {
    id: 5,
    name: "OSCAS — Oasis Second Chance",
    blurb: "Farmway shelter in Sungei Tengah.",
    image: "https://placedog.net/300/300?id=505",
    dogsAvailable: 63,
    email: "adopt@oscas.com.sg",
    website: "https://oscas.com.sg",
    facebook: "https://facebook.com/oscas.sg",
    instagram: "https://instagram.com/oscas_sg",
  },
  {
    id: 6,
    name: "Exclusively Mongrels Ltd",
    blurb: "Local mongrels only. Foster-first.",
    image: "https://placedog.net/300/300?id=506",
    dogsAvailable: 28,
    email: "adopt@exclusivelymongrels.org",
    website: "https://exclusivelymongrels.org",
    facebook: "https://facebook.com/exclusivelymongrels",
    instagram: "https://instagram.com/exclusivelymongrels",
  },
  {
    id: 7,
    name: "Mercylight Animal Sanctuary",
    blurb: "Senior &amp; special-needs animals.",
    image: "https://placedog.net/300/300?id=507",
    dogsAvailable: 47,
    email: "hello@mercylight.sg",
    website: "https://mercylight.sg",
    facebook: "https://facebook.com/MercylightSanctuary",
    instagram: "https://instagram.com/mercylightsanctuary",
    youtube: "https://youtube.com/@mercylight",
  },
  {
    id: 8,
    name: "Purely Adoptions",
    blurb: "Adopt-don't-shop advocacy.",
    image: "https://placedog.net/300/300?id=508",
    dogsAvailable: 19,
    email: "hello@purelyadoptions.com",
    website: "https://purelyadoptions.com",
    facebook: "https://facebook.com/purelyadoptions",
    instagram: "https://instagram.com/purelyadoptions",
    tiktok: "https://tiktok.com/@purelyadoptions",
  },
  {
    id: 9,
    name: "Animal Lovers League",
    blurb: "Cage-free farmway shelter.",
    image: "https://placedog.net/300/300?id=509",
    dogsAvailable: 71,
    email: "adopt@animalloversleague.com",
    website: "https://animalloversleague.com",
    facebook: "https://facebook.com/AnimalLoversLeague",
    instagram: "https://instagram.com/animalloversleague",
  },
  {
    id: 10,
    name: "SPCA Singapore",
    blurb: "Adoption, inspection, advocacy.",
    image: "https://placedog.net/300/300?id=510",
    dogsAvailable: 38,
    email: "adoptions@spca.org.sg",
    website: "https://spca.org.sg",
    facebook: "https://facebook.com/spca.singapore",
    instagram: "https://instagram.com/spcasingapore",
    tiktok: "https://tiktok.com/@spcasingapore",
    youtube: "https://youtube.com/@SPCASingapore",
  },
];
