// Singapore vet directory
window.VETS = [
  {
    id: 1,
    name: "Mount Pleasant Animal Medical Centre",
    address: "232 Whitley Rd",
    hours: "Mon–Sat 9am–7pm · Sun 9am–1pm",
    phone: "+65 6250 8333",
    emergency: true,
    publicHolidays: false,
    area: "Central",
  },
  {
    id: 2,
    name: "Animal Recovery Veterinary Centre",
    address: "30 Burn Rd, #01-01",
    hours: "Open 24 hours",
    phone: "+65 6634 1117",
    emergency: true,
    publicHolidays: true,
    area: "East",
  },
  {
    id: 3,
    name: "Beecroft Animal Specialist & Emergency Hospital",
    address: "5 Burn Rd, #02-01",
    hours: "Open 24 hours",
    phone: "+65 6256 2275",
    emergency: true,
    publicHolidays: true,
    area: "East",
  },
  {
    id: 4,
    name: "The Animal Doctors",
    address: "6 Greenwood Ave",
    hours: "Mon–Fri 10am–8pm · Sat–Sun 10am–6pm",
    phone: "+65 6253 1300",
    emergency: false,
    publicHolidays: false,
    area: "North",
  },
  {
    id: 5,
    name: "The Joyous Vet",
    address: "240 Pasir Panjang Rd",
    hours: "Mon–Sat 10am–8pm · Sun 10am–4pm",
    phone: "+65 6873 3622",
    emergency: false,
    publicHolidays: true,
    area: "West",
  },
  {
    id: 6,
    name: "Light of Life Veterinary Clinic",
    address: "Blk 153 Serangoon North Ave 1",
    hours: "Daily 10am–9pm",
    phone: "+65 6286 0030",
    emergency: false,
    publicHolidays: true,
    area: "Central",
  },
  {
    id: 7,
    name: "Animal & Avian Veterinary Clinic",
    address: "21 Jalan Tua Kong",
    hours: "Mon–Sat 9am–8pm · Sun 9am–5pm",
    phone: "+65 6243 3282",
    emergency: false,
    publicHolidays: false,
    area: "East",
  },
  {
    id: 8,
    name: "The Animal Clinic — Frankel",
    address: "21 Jalan Tua Kong",
    hours: "Mon–Fri 9am–9pm · Sat–Sun 9am–5pm",
    phone: "+65 6244 8009",
    emergency: false,
    publicHolidays: false,
    area: "East",
  },
  {
    id: 9,
    name: "Vet Central",
    address: "62 Eng Watt St",
    hours: "Mon–Sat 10am–8pm",
    phone: "+65 6224 5754",
    emergency: false,
    publicHolidays: false,
    area: "Central",
  },
  {
    id: 10,
    name: "Allpets & Aqualife Veterinary Clinic",
    address: "151 Serangoon North Ave 2",
    hours: "Daily 10am–10pm",
    phone: "+65 6280 3833",
    emergency: false,
    publicHolidays: true,
    area: "North",
  },
  {
    id: 11,
    name: "Companion Animal Surgery",
    address: "162 Bukit Merah Central, #01-3545",
    hours: "Mon–Sat 9am–7pm · Sun 9am–1pm",
    phone: "+65 6271 8488",
    emergency: false,
    publicHolidays: false,
    area: "South",
  },
  {
    id: 12,
    name: "Pet Hospital 24/7 — Tampines",
    address: "1 Tampines North Drive 1",
    hours: "Open 24 hours",
    phone: "+65 6260 7080",
    emergency: true,
    publicHolidays: true,
    area: "East",
  },
];
