/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelfareGroupsRouteImport } from './routes/welfare-groups'
import { Route as VetsRouteImport } from './routes/vets'
import { Route as PetCafesRouteImport } from './routes/pet-cafes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DogRunsRouteImport } from './routes/dog-runs'
import { Route as CustomScriptDotjsRouteImport } from './routes/customScript[.]js'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DogsDogIdRouteImport } from './routes/dogs.$dogId'
import { Route as AdminDogsIndexRouteImport } from './routes/admin.dogs.index'
import { Route as AdminDogsDogIdRouteImport } from './routes/admin.dogs.$dogId'

const WelfareGroupsRoute = WelfareGroupsRouteImport.update({
  id: '/welfare-groups',
  path: '/welfare-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const VetsRoute = VetsRouteImport.update({
  id: '/vets',
  path: '/vets',
  getParentRoute: () => rootRouteImport,
} as any)
const PetCafesRoute = PetCafesRouteImport.update({
  id: '/pet-cafes',
  path: '/pet-cafes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DogRunsRoute = DogRunsRouteImport.update({
  id: '/dog-runs',
  path: '/dog-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomScriptDotjsRoute = CustomScriptDotjsRouteImport.update({
  id: '/customScript.js',
  path: '/customScript.js',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DogsDogIdRoute = DogsDogIdRouteImport.update({
  id: '/dogs/$dogId',
  path: '/dogs/$dogId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDogsIndexRoute = AdminDogsIndexRouteImport.update({
  id: '/admin/dogs/',
  path: '/admin/dogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDogsDogIdRoute = AdminDogsDogIdRouteImport.update({
  id: '/admin/dogs/$dogId',
  path: '/admin/dogs/$dogId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/dog-runs': typeof DogRunsRoute
  '/login': typeof LoginRoute
  '/pet-cafes': typeof PetCafesRoute
  '/vets': typeof VetsRoute
  '/welfare-groups': typeof WelfareGroupsRoute
  '/dogs/$dogId': typeof DogsDogIdRoute
  '/admin/dogs/$dogId': typeof AdminDogsDogIdRoute
  '/admin/dogs/': typeof AdminDogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/dog-runs': typeof DogRunsRoute
  '/login': typeof LoginRoute
  '/pet-cafes': typeof PetCafesRoute
  '/vets': typeof VetsRoute
  '/welfare-groups': typeof WelfareGroupsRoute
  '/dogs/$dogId': typeof DogsDogIdRoute
  '/admin/dogs/$dogId': typeof AdminDogsDogIdRoute
  '/admin/dogs': typeof AdminDogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/dog-runs': typeof DogRunsRoute
  '/login': typeof LoginRoute
  '/pet-cafes': typeof PetCafesRoute
  '/vets': typeof VetsRoute
  '/welfare-groups': typeof WelfareGroupsRoute
  '/dogs/$dogId': typeof DogsDogIdRoute
  '/admin/dogs/$dogId': typeof AdminDogsDogIdRoute
  '/admin/dogs/': typeof AdminDogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customScript.js'
    | '/dog-runs'
    | '/login'
    | '/pet-cafes'
    | '/vets'
    | '/welfare-groups'
    | '/dogs/$dogId'
    | '/admin/dogs/$dogId'
    | '/admin/dogs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customScript.js'
    | '/dog-runs'
    | '/login'
    | '/pet-cafes'
    | '/vets'
    | '/welfare-groups'
    | '/dogs/$dogId'
    | '/admin/dogs/$dogId'
    | '/admin/dogs'
  id:
    | '__root__'
    | '/'
    | '/customScript.js'
    | '/dog-runs'
    | '/login'
    | '/pet-cafes'
    | '/vets'
    | '/welfare-groups'
    | '/dogs/$dogId'
    | '/admin/dogs/$dogId'
    | '/admin/dogs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomScriptDotjsRoute: typeof CustomScriptDotjsRoute
  DogRunsRoute: typeof DogRunsRoute
  LoginRoute: typeof LoginRoute
  PetCafesRoute: typeof PetCafesRoute
  VetsRoute: typeof VetsRoute
  WelfareGroupsRoute: typeof WelfareGroupsRoute
  DogsDogIdRoute: typeof DogsDogIdRoute
  AdminDogsDogIdRoute: typeof AdminDogsDogIdRoute
  AdminDogsIndexRoute: typeof AdminDogsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welfare-groups': {
      id: '/welfare-groups'
      path: '/welfare-groups'
      fullPath: '/welfare-groups'
      preLoaderRoute: typeof WelfareGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vets': {
      id: '/vets'
      path: '/vets'
      fullPath: '/vets'
      preLoaderRoute: typeof VetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pet-cafes': {
      id: '/pet-cafes'
      path: '/pet-cafes'
      fullPath: '/pet-cafes'
      preLoaderRoute: typeof PetCafesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dog-runs': {
      id: '/dog-runs'
      path: '/dog-runs'
      fullPath: '/dog-runs'
      preLoaderRoute: typeof DogRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customScript.js': {
      id: '/customScript.js'
      path: '/customScript.js'
      fullPath: '/customScript.js'
      preLoaderRoute: typeof CustomScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dogs/$dogId': {
      id: '/dogs/$dogId'
      path: '/dogs/$dogId'
      fullPath: '/dogs/$dogId'
      preLoaderRoute: typeof DogsDogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dogs/': {
      id: '/admin/dogs/'
      path: '/admin/dogs'
      fullPath: '/admin/dogs/'
      preLoaderRoute: typeof AdminDogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dogs/$dogId': {
      id: '/admin/dogs/$dogId'
      path: '/admin/dogs/$dogId'
      fullPath: '/admin/dogs/$dogId'
      preLoaderRoute: typeof AdminDogsDogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomScriptDotjsRoute: CustomScriptDotjsRoute,
  DogRunsRoute: DogRunsRoute,
  LoginRoute: LoginRoute,
  PetCafesRoute: PetCafesRoute,
  VetsRoute: VetsRoute,
  WelfareGroupsRoute: WelfareGroupsRoute,
  DogsDogIdRoute: DogsDogIdRoute,
  AdminDogsDogIdRoute: AdminDogsDogIdRoute,
  AdminDogsIndexRoute: AdminDogsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
