/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelfareGroupsRouteImport } from './routes/welfare-groups'
import { Route as VetsRouteImport } from './routes/vets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DogRunsRouteImport } from './routes/dog-runs'
import { Route as CustomScriptDotjsRouteImport } from './routes/customScript[.]js'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminEventsIndexRouteImport } from './routes/admin.events.index'
import { Route as AdminDogsIndexRouteImport } from './routes/admin.dogs.index'

const WelfareGroupsRoute = WelfareGroupsRouteImport.update({
  id: '/welfare-groups',
  path: '/welfare-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const VetsRoute = VetsRouteImport.update({
  id: '/vets',
  path: '/vets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DogRunsRoute = DogRunsRouteImport.update({
  id: '/dog-runs',
  path: '/dog-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomScriptDotjsRoute = CustomScriptDotjsRouteImport.update({
  id: '/customScript.js',
  path: '/customScript.js',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDogsIndexRoute = AdminDogsIndexRouteImport.update({
  id: '/dogs/',
  path: '/dogs/',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/dog-runs': typeof DogRunsRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/vets': typeof VetsRoute
  '/welfare-groups': typeof WelfareGroupsRoute
  '/admin/dogs/': typeof AdminDogsIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/dog-runs': typeof DogRunsRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/vets': typeof VetsRoute
  '/welfare-groups': typeof WelfareGroupsRoute
  '/admin/dogs': typeof AdminDogsIndexRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/dog-runs': typeof DogRunsRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/vets': typeof VetsRoute
  '/welfare-groups': typeof WelfareGroupsRoute
  '/admin/dogs/': typeof AdminDogsIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/customScript.js'
    | '/dog-runs'
    | '/events'
    | '/login'
    | '/vets'
    | '/welfare-groups'
    | '/admin/dogs/'
    | '/admin/events/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/blog'
    | '/customScript.js'
    | '/dog-runs'
    | '/events'
    | '/login'
    | '/vets'
    | '/welfare-groups'
    | '/admin/dogs'
    | '/admin/events'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/customScript.js'
    | '/dog-runs'
    | '/events'
    | '/login'
    | '/vets'
    | '/welfare-groups'
    | '/admin/dogs/'
    | '/admin/events/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRoute
  CustomScriptDotjsRoute: typeof CustomScriptDotjsRoute
  DogRunsRoute: typeof DogRunsRoute
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
  VetsRoute: typeof VetsRoute
  WelfareGroupsRoute: typeof WelfareGroupsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welfare-groups': {
      id: '/welfare-groups'
      path: '/welfare-groups'
      fullPath: '/welfare-groups'
      preLoaderRoute: typeof WelfareGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vets': {
      id: '/vets'
      path: '/vets'
      fullPath: '/vets'
      preLoaderRoute: typeof VetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dog-runs': {
      id: '/dog-runs'
      path: '/dog-runs'
      fullPath: '/dog-runs'
      preLoaderRoute: typeof DogRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customScript.js': {
      id: '/customScript.js'
      path: '/customScript.js'
      fullPath: '/customScript.js'
      preLoaderRoute: typeof CustomScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dogs/': {
      id: '/admin/dogs/'
      path: '/dogs'
      fullPath: '/admin/dogs/'
      preLoaderRoute: typeof AdminDogsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDogsIndexRoute: typeof AdminDogsIndexRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDogsIndexRoute: AdminDogsIndexRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRoute,
  CustomScriptDotjsRoute: CustomScriptDotjsRoute,
  DogRunsRoute: DogRunsRoute,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
  VetsRoute: VetsRoute,
  WelfareGroupsRoute: WelfareGroupsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
